# Copyright (C) 2009 The Android Open Source Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

LOCAL_PATH:= $(call my-dir)
include $(CLEAR_VARS)

#name of the library
LOCAL_MODULE    := FighterPilotRisingSun

#game
MY_GAME_PATH := source/game
MY_GAME_VIEWS_PATH :=  $(MY_GAME_PATH)/views
MY_GAME_COMMON_PATH :=  $(MY_GAME_PATH)/common
MY_GAME_BACKEND_PATH :=  $(MY_GAME_PATH)/backend
MY_GAME_BACKEND_BASIC_CLASSES_PATH :=  $(MY_GAME_BACKEND_PATH)/basicClasses
MY_GAME_BACKEND_GAMEOBJECTS_PATH :=  $(MY_GAME_BACKEND_PATH)/gameObjects
MY_GAME_BACKEND_GAMEOBJECTS_AI_PATH :=  $(MY_GAME_BACKEND_GAMEOBJECTS_PATH)/AI
MY_GAME_BACKEND_GAMEOBJECTS_AIRCRAFTS_PATH :=  $(MY_GAME_BACKEND_GAMEOBJECTS_PATH)/Aircrafts
MY_GAME_BACKEND_GAMEOBJECTS_BUILDINGS_PATH :=  $(MY_GAME_BACKEND_GAMEOBJECTS_PATH)/Buildings
MY_GAME_BACKEND_GAMEOBJECTS_DECOR_PATH :=  $(MY_GAME_BACKEND_GAMEOBJECTS_PATH)/Decor
MY_GAME_BACKEND_GAMEOBJECTS_EVENTS_PATH :=  $(MY_GAME_BACKEND_GAMEOBJECTS_PATH)/Events
MY_GAME_BACKEND_GAMEOBJECTS_EXPLOSIONS_PATH :=  $(MY_GAME_BACKEND_GAMEOBJECTS_PATH)/Explosions
MY_GAME_BACKEND_GAMEOBJECTS_FLOOR_PATH :=  $(MY_GAME_BACKEND_GAMEOBJECTS_PATH)/Floor
MY_GAME_BACKEND_GAMEOBJECTS_GROUND_UNITS_PATH :=  $(MY_GAME_BACKEND_GAMEOBJECTS_PATH)/GroundUnits
MY_GAME_BACKEND_GAMEOBJECTS_MAPS_PATH :=  $(MY_GAME_BACKEND_GAMEOBJECTS_PATH)/Maps
MY_GAME_BACKEND_GAMEOBJECTS_PROJECTILES_PATH :=  $(MY_GAME_BACKEND_GAMEOBJECTS_PATH)/Projectiles
MY_GAME_BACKEND_GAMEOBJECTS_SHIPS_PATH :=  $(MY_GAME_BACKEND_GAMEOBJECTS_PATH)/Ships
MY_GAME_BACKEND_GAMEOBJECTS_WEAPONS_PATH :=  $(MY_GAME_BACKEND_GAMEOBJECTS_PATH)/Weapons

#core
MY_CORE_PATH := source/core
MY_CORE_UTILTIY_PATH := $(MY_CORE_PATH)/utility
MY_CORE_STD_LIB_PATH := $(MY_CORE_PATH)/standardLibrary
MY_CORE_SOUND_PATH :=  $(MY_CORE_PATH)/sound
MY_CORE_GRAPHICS_PATH :=  $(MY_CORE_PATH)/graphic
MY_CORE_VIEWS_PATH :=  $(MY_CORE_PATH)/views
MY_CORE_COMPONENTS_PATH :=  $(MY_CORE_VIEWS_PATH)/components
MY_CORE_POPUPS_PATH :=  $(MY_CORE_VIEWS_PATH)/popups
MY_CORE_TRANSITIONS_PATH :=  $(MY_CORE_VIEWS_PATH)/transitions
MY_CORE_COLLISION_PATH :=  $(MY_CORE_PATH)/collision
MY_CORE_CRYPTOGRAPHY_PATH :=  $(MY_CORE_PATH)/cryptography

#native
MY_NATIVE_PATH := source/native
MY_NATIVE_UTILITY_PATH := $(MY_NATIVE_PATH)/utility

#-------------------------------- GAME ------------------------------- #

#Add Game classes here
LOCAL_SRC_FILES +=  $(MY_GAME_PATH)/CFighterPilotThePacificWar.cpp

#Add View classes here
LOCAL_SRC_FILES += $(MY_GAME_VIEWS_PATH)/CMainMenuView.cpp
LOCAL_SRC_FILES += $(MY_GAME_VIEWS_PATH)/CMainMenuExitView.cpp
LOCAL_SRC_FILES += $(MY_GAME_VIEWS_PATH)/CChooseCampaignView.cpp
LOCAL_SRC_FILES += $(MY_GAME_VIEWS_PATH)/CCampaignScreen.cpp
LOCAL_SRC_FILES += $(MY_GAME_VIEWS_PATH)/CCampaignBriefingScreen.cpp
LOCAL_SRC_FILES += $(MY_GAME_VIEWS_PATH)/CLoadingScreen.cpp
LOCAL_SRC_FILES += $(MY_GAME_VIEWS_PATH)/CMissionBriefingView.cpp
LOCAL_SRC_FILES += $(MY_GAME_VIEWS_PATH)/CGameView.cpp
LOCAL_SRC_FILES += $(MY_GAME_VIEWS_PATH)/CGamePauseView.cpp
LOCAL_SRC_FILES += $(MY_GAME_VIEWS_PATH)/CCompanyImageView.cpp
LOCAL_SRC_FILES += $(MY_GAME_VIEWS_PATH)/CGameSettingsView.cpp
LOCAL_SRC_FILES += $(MY_GAME_VIEWS_PATH)/CChangeSongView.cpp
LOCAL_SRC_FILES += $(MY_GAME_VIEWS_PATH)/CCreditsView.cpp
LOCAL_SRC_FILES += $(MY_GAME_VIEWS_PATH)/CSelectLanguageView.cpp
LOCAL_SRC_FILES += $(MY_GAME_VIEWS_PATH)/CMissionVictoryView.cpp
LOCAL_SRC_FILES += $(MY_GAME_VIEWS_PATH)/CTutorialView.cpp
LOCAL_SRC_FILES += $(MY_GAME_VIEWS_PATH)/CHighscoresView.cpp
LOCAL_SRC_FILES += $(MY_GAME_VIEWS_PATH)/CMissionHighscoresView.cpp
LOCAL_SRC_FILES += $(MY_GAME_VIEWS_PATH)/CAgreeToTermsScreen.cpp
LOCAL_SRC_FILES += $(MY_GAME_VIEWS_PATH)/CEndMissionTempTransitionView.cpp

#Add Common classes here
LOCAL_SRC_FILES += $(MY_GAME_COMMON_PATH)/CSaveGameObject.cpp
LOCAL_SRC_FILES += $(MY_GAME_COMMON_PATH)/CGameVariables.cpp
LOCAL_SRC_FILES += $(MY_GAME_COMMON_PATH)/CUserStats.cpp

#Add Backend classes here
LOCAL_SRC_FILES += $(MY_GAME_BACKEND_PATH)/CBombingGuidingSystem.cpp
LOCAL_SRC_FILES += $(MY_GAME_BACKEND_PATH)/CClockTimer.cpp
LOCAL_SRC_FILES += $(MY_GAME_BACKEND_PATH)/CGameData.cpp
LOCAL_SRC_FILES += $(MY_GAME_BACKEND_PATH)/CInterval.cpp
LOCAL_SRC_FILES += $(MY_GAME_BACKEND_PATH)/CGameObjectManager.cpp
LOCAL_SRC_FILES += $(MY_GAME_BACKEND_PATH)/CHeavyBomberLocator.cpp
LOCAL_SRC_FILES += $(MY_GAME_BACKEND_PATH)/CHeightoMeter.cpp
LOCAL_SRC_FILES += $(MY_GAME_BACKEND_PATH)/CHud.cpp
LOCAL_SRC_FILES += $(MY_GAME_BACKEND_PATH)/CPlayer.cpp
LOCAL_SRC_FILES += $(MY_GAME_BACKEND_PATH)/CSmallPlaneLocator.cpp
LOCAL_SRC_FILES += $(MY_GAME_BACKEND_PATH)/CSpeedoMeter.cpp
LOCAL_SRC_FILES += $(MY_GAME_BACKEND_PATH)/CStatsTracker.cpp
LOCAL_SRC_FILES += $(MY_GAME_BACKEND_PATH)/CTouchControls.cpp
LOCAL_SRC_FILES += $(MY_GAME_BACKEND_PATH)/CTouchScreenToRespawnReminder.cpp

#Add Basic classes here
LOCAL_SRC_FILES += $(MY_GAME_BACKEND_BASIC_CLASSES_PATH)/CAircraft.cpp
LOCAL_SRC_FILES += $(MY_GAME_BACKEND_BASIC_CLASSES_PATH)/CBackgroundImage.cpp
LOCAL_SRC_FILES += $(MY_GAME_BACKEND_BASIC_CLASSES_PATH)/CBuilding.cpp
LOCAL_SRC_FILES += $(MY_GAME_BACKEND_BASIC_CLASSES_PATH)/CDrawObject.cpp
LOCAL_SRC_FILES += $(MY_GAME_BACKEND_BASIC_CLASSES_PATH)/CEvent.cpp
LOCAL_SRC_FILES += $(MY_GAME_BACKEND_BASIC_CLASSES_PATH)/CGameObject.cpp
LOCAL_SRC_FILES += $(MY_GAME_BACKEND_BASIC_CLASSES_PATH)/CLandingSurface.cpp
LOCAL_SRC_FILES += $(MY_GAME_BACKEND_BASIC_CLASSES_PATH)/CMap.cpp
LOCAL_SRC_FILES += $(MY_GAME_BACKEND_BASIC_CLASSES_PATH)/CMoveableGameObject.cpp
LOCAL_SRC_FILES += $(MY_GAME_BACKEND_BASIC_CLASSES_PATH)/CPlaneWheels.cpp
LOCAL_SRC_FILES += $(MY_GAME_BACKEND_BASIC_CLASSES_PATH)/CProjectile.cpp
LOCAL_SRC_FILES += $(MY_GAME_BACKEND_BASIC_CLASSES_PATH)/CWeapon.cpp
LOCAL_SRC_FILES += $(MY_GAME_BACKEND_BASIC_CLASSES_PATH)/CWeaponAttached.cpp
LOCAL_SRC_FILES += $(MY_GAME_BACKEND_BASIC_CLASSES_PATH)/CWeaponAttachedInvisible.cpp
LOCAL_SRC_FILES += $(MY_GAME_BACKEND_BASIC_CLASSES_PATH)/CWeaponBomb.cpp
LOCAL_SRC_FILES += $(MY_GAME_BACKEND_BASIC_CLASSES_PATH)/CShip.cpp
LOCAL_SRC_FILES += $(MY_GAME_BACKEND_BASIC_CLASSES_PATH)/CProjectileBomb.cpp
LOCAL_SRC_FILES += $(MY_GAME_BACKEND_BASIC_CLASSES_PATH)/CBasicExplosion.cpp
LOCAL_SRC_FILES += $(MY_GAME_BACKEND_BASIC_CLASSES_PATH)/CGravitationalProjectile.cpp
LOCAL_SRC_FILES += $(MY_GAME_BACKEND_BASIC_CLASSES_PATH)/CMobileAAGun.cpp
LOCAL_SRC_FILES += $(MY_GAME_BACKEND_BASIC_CLASSES_PATH)/CMobileRotatingWeapon.cpp
LOCAL_SRC_FILES += $(MY_GAME_BACKEND_BASIC_CLASSES_PATH)/CAAArterially.cpp
LOCAL_SRC_FILES += $(MY_GAME_BACKEND_BASIC_CLASSES_PATH)/CShipCarrier.cpp
LOCAL_SRC_FILES += $(MY_GAME_BACKEND_BASIC_CLASSES_PATH)/CBasicTutorialMap.cpp
LOCAL_SRC_FILES += $(MY_GAME_BACKEND_BASIC_CLASSES_PATH)/CGroundUnit.cpp
LOCAL_SRC_FILES += $(MY_GAME_BACKEND_BASIC_CLASSES_PATH)/CTimeEvent.cpp

#Add Game Object classes here
LOCAL_SRC_FILES += $(MY_GAME_BACKEND_GAMEOBJECTS_PATH)/CGameObjectDefaultValues.cpp

#Add AI classes here
LOCAL_SRC_FILES += $(MY_GAME_BACKEND_GAMEOBJECTS_AI_PATH)/CHeavyBomberAI.cpp
LOCAL_SRC_FILES += $(MY_GAME_BACKEND_GAMEOBJECTS_AI_PATH)/CFighterAI.cpp
LOCAL_SRC_FILES += $(MY_GAME_BACKEND_GAMEOBJECTS_AI_PATH)/CFighterAIAttack.cpp
LOCAL_SRC_FILES += $(MY_GAME_BACKEND_GAMEOBJECTS_AI_PATH)/CFighterAIBomb.cpp
LOCAL_SRC_FILES += $(MY_GAME_BACKEND_GAMEOBJECTS_AI_PATH)/CFighterAIShipBomb.cpp
LOCAL_SRC_FILES += $(MY_GAME_BACKEND_GAMEOBJECTS_AI_PATH)/CBackCannonAI.cpp
LOCAL_SRC_FILES += $(MY_GAME_BACKEND_GAMEOBJECTS_AI_PATH)/CAAArteriallyAI.cpp
LOCAL_SRC_FILES += $(MY_GAME_BACKEND_GAMEOBJECTS_AI_PATH)/CShipArteriallyAI.cpp
LOCAL_SRC_FILES += $(MY_GAME_BACKEND_GAMEOBJECTS_AI_PATH)/CGroundUnitOverlordAI.cpp

#Add Aircraft classes here
LOCAL_SRC_FILES += $(MY_GAME_BACKEND_GAMEOBJECTS_AIRCRAFTS_PATH)/CDauntless.cpp
LOCAL_SRC_FILES += $(MY_GAME_BACKEND_GAMEOBJECTS_AIRCRAFTS_PATH)/CVal.cpp
LOCAL_SRC_FILES += $(MY_GAME_BACKEND_GAMEOBJECTS_AIRCRAFTS_PATH)/CBetty.cpp
LOCAL_SRC_FILES += $(MY_GAME_BACKEND_GAMEOBJECTS_AIRCRAFTS_PATH)/CMitchell.cpp

#Add Buildings here
LOCAL_SRC_FILES += $(MY_GAME_BACKEND_GAMEOBJECTS_BUILDINGS_PATH)/CAirport.cpp
LOCAL_SRC_FILES += $(MY_GAME_BACKEND_GAMEOBJECTS_BUILDINGS_PATH)/CComStation.cpp
LOCAL_SRC_FILES += $(MY_GAME_BACKEND_GAMEOBJECTS_BUILDINGS_PATH)/CFlagPole.cpp
LOCAL_SRC_FILES += $(MY_GAME_BACKEND_GAMEOBJECTS_BUILDINGS_PATH)/CHangar.cpp
LOCAL_SRC_FILES += $(MY_GAME_BACKEND_GAMEOBJECTS_BUILDINGS_PATH)/CHq.cpp
LOCAL_SRC_FILES += $(MY_GAME_BACKEND_GAMEOBJECTS_BUILDINGS_PATH)/CJapaneseAA20mmMachineCannon.cpp
LOCAL_SRC_FILES += $(MY_GAME_BACKEND_GAMEOBJECTS_BUILDINGS_PATH)/CJapaneseAA75mmType88.cpp
LOCAL_SRC_FILES += $(MY_GAME_BACKEND_GAMEOBJECTS_BUILDINGS_PATH)/CJapaneseAAConcrete.cpp

#Add Decor classes here
LOCAL_SRC_FILES += $(MY_GAME_BACKEND_GAMEOBJECTS_DECOR_PATH)/CAircraftSmokeCreator.cpp
LOCAL_SRC_FILES += $(MY_GAME_BACKEND_GAMEOBJECTS_DECOR_PATH)/CGeneralSmokeCreator.cpp
LOCAL_SRC_FILES += $(MY_GAME_BACKEND_GAMEOBJECTS_DECOR_PATH)/CSmoke.cpp
LOCAL_SRC_FILES += $(MY_GAME_BACKEND_GAMEOBJECTS_DECOR_PATH)/CBigTree.cpp
LOCAL_SRC_FILES += $(MY_GAME_BACKEND_GAMEOBJECTS_DECOR_PATH)/CForest1.cpp
LOCAL_SRC_FILES += $(MY_GAME_BACKEND_GAMEOBJECTS_DECOR_PATH)/CForest2.cpp
LOCAL_SRC_FILES += $(MY_GAME_BACKEND_GAMEOBJECTS_DECOR_PATH)/CForest3.cpp
LOCAL_SRC_FILES += $(MY_GAME_BACKEND_GAMEOBJECTS_DECOR_PATH)/CForest4.cpp
LOCAL_SRC_FILES += $(MY_GAME_BACKEND_GAMEOBJECTS_DECOR_PATH)/CSmallTree.cpp
LOCAL_SRC_FILES += $(MY_GAME_BACKEND_GAMEOBJECTS_DECOR_PATH)/CTree1.cpp
LOCAL_SRC_FILES += $(MY_GAME_BACKEND_GAMEOBJECTS_DECOR_PATH)/CTree2.cpp

#Add Events classes here
LOCAL_SRC_FILES += $(MY_GAME_BACKEND_GAMEOBJECTS_EVENTS_PATH)/CClockTimerEvent.cpp
LOCAL_SRC_FILES += $(MY_GAME_BACKEND_GAMEOBJECTS_EVENTS_PATH)/CCreateMitchellToAttackTargetClockTimer.cpp
LOCAL_SRC_FILES += $(MY_GAME_BACKEND_GAMEOBJECTS_EVENTS_PATH)/CGetBonusPointsIfLessTroopsGetKilled.cpp
LOCAL_SRC_FILES += $(MY_GAME_BACKEND_GAMEOBJECTS_EVENTS_PATH)/CGetBonusPointsIfObjectsAreDestroyedEvent.cpp
LOCAL_SRC_FILES += $(MY_GAME_BACKEND_GAMEOBJECTS_EVENTS_PATH)/CGetBonusPointsIfObjectsSurvive.cpp
LOCAL_SRC_FILES += $(MY_GAME_BACKEND_GAMEOBJECTS_EVENTS_PATH)/CLoseIfObjectLeavesMap.cpp
LOCAL_SRC_FILES += $(MY_GAME_BACKEND_GAMEOBJECTS_EVENTS_PATH)/CLoseIfObjectsAreCaptured.cpp
LOCAL_SRC_FILES += $(MY_GAME_BACKEND_GAMEOBJECTS_EVENTS_PATH)/CLoseIfObjectsAreDestroyedEvent.cpp
LOCAL_SRC_FILES += $(MY_GAME_BACKEND_GAMEOBJECTS_EVENTS_PATH)/CSpawnAmericanLCTEveryTimeInterval.cpp
LOCAL_SRC_FILES += $(MY_GAME_BACKEND_GAMEOBJECTS_EVENTS_PATH)/CSpawnAmericanSquadEveryTimeInterval.cpp
LOCAL_SRC_FILES += $(MY_GAME_BACKEND_GAMEOBJECTS_EVENTS_PATH)/CSpawnAmericanTroopTransporterIfObjectsDestroyed.cpp
LOCAL_SRC_FILES += $(MY_GAME_BACKEND_GAMEOBJECTS_EVENTS_PATH)/CSpawnBettyEveryTimeInterval.cpp
LOCAL_SRC_FILES += $(MY_GAME_BACKEND_GAMEOBJECTS_EVENTS_PATH)/CSpawnBettyIfBuildingGetsCaptured.cpp
LOCAL_SRC_FILES += $(MY_GAME_BACKEND_GAMEOBJECTS_EVENTS_PATH)/CSpawnDauntlessEveryTimeInterval.cpp
LOCAL_SRC_FILES += $(MY_GAME_BACKEND_GAMEOBJECTS_EVENTS_PATH)/CSpawnDauntlessIfBuildingGetsCaptured.cpp
LOCAL_SRC_FILES += $(MY_GAME_BACKEND_GAMEOBJECTS_EVENTS_PATH)/CSpawnJapaneseSquadEveryTimeInterval.cpp
LOCAL_SRC_FILES += $(MY_GAME_BACKEND_GAMEOBJECTS_EVENTS_PATH)/CSpawnJapaneseSquadIfBuildingGetsCaptured.cpp
LOCAL_SRC_FILES += $(MY_GAME_BACKEND_GAMEOBJECTS_EVENTS_PATH)/CSpawnMitchellEveryTimeInterval.cpp
LOCAL_SRC_FILES += $(MY_GAME_BACKEND_GAMEOBJECTS_EVENTS_PATH)/CSpawnValEveryTimeInterval.cpp
LOCAL_SRC_FILES += $(MY_GAME_BACKEND_GAMEOBJECTS_EVENTS_PATH)/CSpawnValIfBuildingGetsCaptured.cpp
LOCAL_SRC_FILES += $(MY_GAME_BACKEND_GAMEOBJECTS_EVENTS_PATH)/CWinIfAllJapaneseForcesAreDestroyed.cpp
LOCAL_SRC_FILES += $(MY_GAME_BACKEND_GAMEOBJECTS_EVENTS_PATH)/CWinIfAllJapaneseMoveableObjectsAreDestroyed.cpp
LOCAL_SRC_FILES += $(MY_GAME_BACKEND_GAMEOBJECTS_EVENTS_PATH)/CWinIfJapaneseDestroyedAfterACertainTime.cpp
LOCAL_SRC_FILES += $(MY_GAME_BACKEND_GAMEOBJECTS_EVENTS_PATH)/CWinIfObjectsAreCaptured.cpp
LOCAL_SRC_FILES += $(MY_GAME_BACKEND_GAMEOBJECTS_EVENTS_PATH)/CWinIfObjectsAreDestroyedEvent.cpp
LOCAL_SRC_FILES += $(MY_GAME_BACKEND_GAMEOBJECTS_EVENTS_PATH)/CWinIfObjectsLeaveMapAlive.cpp
#Add Tutorial Events
LOCAL_SRC_FILES += $(MY_GAME_BACKEND_GAMEOBJECTS_EVENTS_PATH)/TutorialEvents/CBasicAircraftNeededTutorialClass.cpp
LOCAL_SRC_FILES += $(MY_GAME_BACKEND_GAMEOBJECTS_EVENTS_PATH)/TutorialEvents/CBasicTutorialClass.cpp
LOCAL_SRC_FILES += $(MY_GAME_BACKEND_GAMEOBJECTS_EVENTS_PATH)/TutorialEvents/CControlsTutorialLandOnCarrier.cpp
LOCAL_SRC_FILES += $(MY_GAME_BACKEND_GAMEOBJECTS_EVENTS_PATH)/TutorialEvents/CControlsTutorialLooping.cpp
LOCAL_SRC_FILES += $(MY_GAME_BACKEND_GAMEOBJECTS_EVENTS_PATH)/TutorialEvents/CControlsTutorialMoveToEndOfMap.cpp
LOCAL_SRC_FILES += $(MY_GAME_BACKEND_GAMEOBJECTS_EVENTS_PATH)/TutorialEvents/CControlsTutorialSlowDown.cpp
LOCAL_SRC_FILES += $(MY_GAME_BACKEND_GAMEOBJECTS_EVENTS_PATH)/TutorialEvents/CControlsTutorialSpeedUp.cpp
LOCAL_SRC_FILES += $(MY_GAME_BACKEND_GAMEOBJECTS_EVENTS_PATH)/TutorialEvents/CControlsTutorialStartFromCarrier.cpp
LOCAL_SRC_FILES += $(MY_GAME_BACKEND_GAMEOBJECTS_EVENTS_PATH)/TutorialEvents/CControlsTutorialTurns.cpp
LOCAL_SRC_FILES += $(MY_GAME_BACKEND_GAMEOBJECTS_EVENTS_PATH)/TutorialEvents/CControlsTutorialZoomInAndZoomOut.cpp
LOCAL_SRC_FILES += $(MY_GAME_BACKEND_GAMEOBJECTS_EVENTS_PATH)/TutorialEvents/CRestartLastTutorialScreenIfDiedEvent.cpp
LOCAL_SRC_FILES += $(MY_GAME_BACKEND_GAMEOBJECTS_EVENTS_PATH)/TutorialEvents/CWeaponsTutorialAttackBomber.cpp
LOCAL_SRC_FILES += $(MY_GAME_BACKEND_GAMEOBJECTS_EVENTS_PATH)/TutorialEvents/CWeaponsTutorialAttackFighter.cpp
LOCAL_SRC_FILES += $(MY_GAME_BACKEND_GAMEOBJECTS_EVENTS_PATH)/TutorialEvents/CWeaponsTutorialAttackShip.cpp
LOCAL_SRC_FILES += $(MY_GAME_BACKEND_GAMEOBJECTS_EVENTS_PATH)/TutorialEvents/CWeaponsTutorialBomb1000kg.cpp
LOCAL_SRC_FILES += $(MY_GAME_BACKEND_GAMEOBJECTS_EVENTS_PATH)/TutorialEvents/CWeaponsTutorialDiveBombingKill.cpp
LOCAL_SRC_FILES += $(MY_GAME_BACKEND_GAMEOBJECTS_EVENTS_PATH)/TutorialEvents/CWeaponsTutorialFireButtons.cpp
LOCAL_SRC_FILES += $(MY_GAME_BACKEND_GAMEOBJECTS_EVENTS_PATH)/TutorialEvents/CWeaponsTutorialKillSoldiersUsingMachineGun.cpp
LOCAL_SRC_FILES += $(MY_GAME_BACKEND_GAMEOBJECTS_EVENTS_PATH)/TutorialEvents/CWeaponsTutorialLoseIfAllAmericanSoldiersDied.cpp
LOCAL_SRC_FILES += $(MY_GAME_BACKEND_GAMEOBJECTS_EVENTS_PATH)/TutorialEvents/CWeaponsTutorialLoseIfFailedToKillAnything.cpp

#Add Explosions here
LOCAL_SRC_FILES += $(MY_GAME_BACKEND_GAMEOBJECTS_EXPLOSIONS_PATH)/CExplosion1000Kg.cpp
LOCAL_SRC_FILES += $(MY_GAME_BACKEND_GAMEOBJECTS_EXPLOSIONS_PATH)/CExplosion1000KgInAir.cpp
LOCAL_SRC_FILES += $(MY_GAME_BACKEND_GAMEOBJECTS_EXPLOSIONS_PATH)/CExplosion1000KgInWater.cpp
LOCAL_SRC_FILES += $(MY_GAME_BACKEND_GAMEOBJECTS_EXPLOSIONS_PATH)/CExplosion500Kg.cpp
LOCAL_SRC_FILES += $(MY_GAME_BACKEND_GAMEOBJECTS_EXPLOSIONS_PATH)/CExplosion500KgInAir.cpp
LOCAL_SRC_FILES += $(MY_GAME_BACKEND_GAMEOBJECTS_EXPLOSIONS_PATH)/CExplosion500KgInWater.cpp
LOCAL_SRC_FILES += $(MY_GAME_BACKEND_GAMEOBJECTS_EXPLOSIONS_PATH)/CExplosion100Kg.cpp
LOCAL_SRC_FILES += $(MY_GAME_BACKEND_GAMEOBJECTS_EXPLOSIONS_PATH)/CExplosion100KgInAir.cpp
LOCAL_SRC_FILES += $(MY_GAME_BACKEND_GAMEOBJECTS_EXPLOSIONS_PATH)/CExplosion100KgInWater.cpp
LOCAL_SRC_FILES += $(MY_GAME_BACKEND_GAMEOBJECTS_EXPLOSIONS_PATH)/CExplosion14InchShell.cpp
LOCAL_SRC_FILES += $(MY_GAME_BACKEND_GAMEOBJECTS_EXPLOSIONS_PATH)/CExplosion14InchShellInWater.cpp
LOCAL_SRC_FILES += $(MY_GAME_BACKEND_GAMEOBJECTS_EXPLOSIONS_PATH)/CWaterSplash.cpp

#Add Floor here
LOCAL_SRC_FILES += $(MY_GAME_BACKEND_GAMEOBJECTS_FLOOR_PATH)/CFloorLand.cpp
LOCAL_SRC_FILES += $(MY_GAME_BACKEND_GAMEOBJECTS_FLOOR_PATH)/CFloorWater.cpp

#Add Ground Units here
LOCAL_SRC_FILES += $(MY_GAME_BACKEND_GAMEOBJECTS_GROUND_UNITS_PATH)/CAmericanAAShermanTank.cpp
LOCAL_SRC_FILES += $(MY_GAME_BACKEND_GAMEOBJECTS_GROUND_UNITS_PATH)/CAmericanRifleman.cpp
LOCAL_SRC_FILES += $(MY_GAME_BACKEND_GAMEOBJECTS_GROUND_UNITS_PATH)/CAmericanRocketman.cpp
LOCAL_SRC_FILES += $(MY_GAME_BACKEND_GAMEOBJECTS_GROUND_UNITS_PATH)/CAmericanShermanTank.cpp
LOCAL_SRC_FILES += $(MY_GAME_BACKEND_GAMEOBJECTS_GROUND_UNITS_PATH)/CAmericanSquad.cpp
LOCAL_SRC_FILES += $(MY_GAME_BACKEND_GAMEOBJECTS_GROUND_UNITS_PATH)/CBasicSquad.cpp
LOCAL_SRC_FILES += $(MY_GAME_BACKEND_GAMEOBJECTS_GROUND_UNITS_PATH)/CJapanese97ChiHaTank.cpp
LOCAL_SRC_FILES += $(MY_GAME_BACKEND_GAMEOBJECTS_GROUND_UNITS_PATH)/CJapaneseAA97ChiHaTank.cpp
LOCAL_SRC_FILES += $(MY_GAME_BACKEND_GAMEOBJECTS_GROUND_UNITS_PATH)/CJapaneseRifleman.cpp
LOCAL_SRC_FILES += $(MY_GAME_BACKEND_GAMEOBJECTS_GROUND_UNITS_PATH)/CJapaneseRocketman.cpp
LOCAL_SRC_FILES += $(MY_GAME_BACKEND_GAMEOBJECTS_GROUND_UNITS_PATH)/CJapaneseSquad.cpp

#Add Maps classes here
LOCAL_SRC_FILES += $(MY_GAME_BACKEND_GAMEOBJECTS_MAPS_PATH)/CTutorial1Map.cpp
LOCAL_SRC_FILES += $(MY_GAME_BACKEND_GAMEOBJECTS_MAPS_PATH)/CTutorial2Map.cpp
LOCAL_SRC_FILES += $(MY_GAME_BACKEND_GAMEOBJECTS_MAPS_PATH)/CTutorial3Map.cpp
LOCAL_SRC_FILES += $(MY_GAME_BACKEND_GAMEOBJECTS_MAPS_PATH)/CCampaign1Map1.cpp
LOCAL_SRC_FILES += $(MY_GAME_BACKEND_GAMEOBJECTS_MAPS_PATH)/CCampaign1Map2.cpp
LOCAL_SRC_FILES += $(MY_GAME_BACKEND_GAMEOBJECTS_MAPS_PATH)/CCampaign1Map3.cpp
LOCAL_SRC_FILES += $(MY_GAME_BACKEND_GAMEOBJECTS_MAPS_PATH)/CCampaign1Map4.cpp
LOCAL_SRC_FILES += $(MY_GAME_BACKEND_GAMEOBJECTS_MAPS_PATH)/CCampaign2Map1.cpp
LOCAL_SRC_FILES += $(MY_GAME_BACKEND_GAMEOBJECTS_MAPS_PATH)/CCampaign2Map2.cpp
LOCAL_SRC_FILES += $(MY_GAME_BACKEND_GAMEOBJECTS_MAPS_PATH)/CCampaign2Map3.cpp
LOCAL_SRC_FILES += $(MY_GAME_BACKEND_GAMEOBJECTS_MAPS_PATH)/CCampaign2Map4.cpp
LOCAL_SRC_FILES += $(MY_GAME_BACKEND_GAMEOBJECTS_MAPS_PATH)/CCampaign3Map1.cpp
LOCAL_SRC_FILES += $(MY_GAME_BACKEND_GAMEOBJECTS_MAPS_PATH)/CCampaign3Map2.cpp
LOCAL_SRC_FILES += $(MY_GAME_BACKEND_GAMEOBJECTS_MAPS_PATH)/CCampaign3Map3.cpp
LOCAL_SRC_FILES += $(MY_GAME_BACKEND_GAMEOBJECTS_MAPS_PATH)/CCampaign3Map4.cpp
LOCAL_SRC_FILES += $(MY_GAME_BACKEND_GAMEOBJECTS_MAPS_PATH)/CCampaign4Map1.cpp
LOCAL_SRC_FILES += $(MY_GAME_BACKEND_GAMEOBJECTS_MAPS_PATH)/CCampaign4Map2.cpp
LOCAL_SRC_FILES += $(MY_GAME_BACKEND_GAMEOBJECTS_MAPS_PATH)/CCampaign4Map3.cpp
LOCAL_SRC_FILES += $(MY_GAME_BACKEND_GAMEOBJECTS_MAPS_PATH)/CCampaign4Map4.cpp

#Add Projectiles here
LOCAL_SRC_FILES += $(MY_GAME_BACKEND_GAMEOBJECTS_PROJECTILES_PATH)/CBomb1000kg.cpp
LOCAL_SRC_FILES += $(MY_GAME_BACKEND_GAMEOBJECTS_PROJECTILES_PATH)/CBomb500kg.cpp
LOCAL_SRC_FILES += $(MY_GAME_BACKEND_GAMEOBJECTS_PROJECTILES_PATH)/CBomb100kg.cpp
LOCAL_SRC_FILES += $(MY_GAME_BACKEND_GAMEOBJECTS_PROJECTILES_PATH)/CBulletCannon20mm.cpp
LOCAL_SRC_FILES += $(MY_GAME_BACKEND_GAMEOBJECTS_PROJECTILES_PATH)/CBullet13mm.cpp
LOCAL_SRC_FILES += $(MY_GAME_BACKEND_GAMEOBJECTS_PROJECTILES_PATH)/CBullet8mm.cpp
LOCAL_SRC_FILES += $(MY_GAME_BACKEND_GAMEOBJECTS_PROJECTILES_PATH)/CClusterBomb.cpp
LOCAL_SRC_FILES += $(MY_GAME_BACKEND_GAMEOBJECTS_PROJECTILES_PATH)/CStandardRocket.cpp
LOCAL_SRC_FILES += $(MY_GAME_BACKEND_GAMEOBJECTS_PROJECTILES_PATH)/CTorpedo.cpp
LOCAL_SRC_FILES += $(MY_GAME_BACKEND_GAMEOBJECTS_PROJECTILES_PATH)/CUnderWaterTorpedo.cpp
LOCAL_SRC_FILES += $(MY_GAME_BACKEND_GAMEOBJECTS_PROJECTILES_PATH)/CBulletRifle.cpp
LOCAL_SRC_FILES += $(MY_GAME_BACKEND_GAMEOBJECTS_PROJECTILES_PATH)/CExplosive14InchShell.cpp
LOCAL_SRC_FILES += $(MY_GAME_BACKEND_GAMEOBJECTS_PROJECTILES_PATH)/CExplosive7InchShell.cpp
LOCAL_SRC_FILES += $(MY_GAME_BACKEND_GAMEOBJECTS_PROJECTILES_PATH)/CExplosive75mmShell.cpp
LOCAL_SRC_FILES += $(MY_GAME_BACKEND_GAMEOBJECTS_PROJECTILES_PATH)/CExplosive88mmShell.cpp
LOCAL_SRC_FILES += $(MY_GAME_BACKEND_GAMEOBJECTS_PROJECTILES_PATH)/CPropelledGrenade.cpp
LOCAL_SRC_FILES += $(MY_GAME_BACKEND_GAMEOBJECTS_PROJECTILES_PATH)/CTankShell80mm.cpp

#Add Ships here
LOCAL_SRC_FILES += $(MY_GAME_BACKEND_GAMEOBJECTS_SHIPS_PATH)/CAmericanBattleshipUSSTennessee.cpp
LOCAL_SRC_FILES += $(MY_GAME_BACKEND_GAMEOBJECTS_SHIPS_PATH)/CAmericanCarrierLexington.cpp
LOCAL_SRC_FILES += $(MY_GAME_BACKEND_GAMEOBJECTS_SHIPS_PATH)/CAmericanDestroyer.cpp
LOCAL_SRC_FILES += $(MY_GAME_BACKEND_GAMEOBJECTS_SHIPS_PATH)/CAmericanLCT.cpp
LOCAL_SRC_FILES += $(MY_GAME_BACKEND_GAMEOBJECTS_SHIPS_PATH)/CAmericanTroopTransporter.cpp
LOCAL_SRC_FILES += $(MY_GAME_BACKEND_GAMEOBJECTS_SHIPS_PATH)/CJapaneseBattleshipYamato.cpp
LOCAL_SRC_FILES += $(MY_GAME_BACKEND_GAMEOBJECTS_SHIPS_PATH)/CJapaneseCarrierShokaku.cpp
LOCAL_SRC_FILES += $(MY_GAME_BACKEND_GAMEOBJECTS_SHIPS_PATH)/CJapaneseCarrierTaiho.cpp
LOCAL_SRC_FILES += $(MY_GAME_BACKEND_GAMEOBJECTS_SHIPS_PATH)/CJapaneseOilTanker.cpp
LOCAL_SRC_FILES += $(MY_GAME_BACKEND_GAMEOBJECTS_SHIPS_PATH)/CJapaneseTroopTransporter.cpp
LOCAL_SRC_FILES += $(MY_GAME_BACKEND_GAMEOBJECTS_SHIPS_PATH)/CJapaneseCarrierShoho.cpp
LOCAL_SRC_FILES += $(MY_GAME_BACKEND_GAMEOBJECTS_SHIPS_PATH)/CJapaneseDestroyer.cpp
LOCAL_SRC_FILES += $(MY_GAME_BACKEND_GAMEOBJECTS_SHIPS_PATH)/CUSSVictory.cpp
LOCAL_SRC_FILES += $(MY_GAME_BACKEND_GAMEOBJECTS_SHIPS_PATH)/CJapaneseLCT.cpp

#Add Weapons here
LOCAL_SRC_FILES += $(MY_GAME_BACKEND_GAMEOBJECTS_WEAPONS_PATH)/CExplosive14InchGun.cpp
LOCAL_SRC_FILES += $(MY_GAME_BACKEND_GAMEOBJECTS_WEAPONS_PATH)/CExplosive7InchGun.cpp
LOCAL_SRC_FILES += $(MY_GAME_BACKEND_GAMEOBJECTS_WEAPONS_PATH)/CGrenadeLauncher.cpp
LOCAL_SRC_FILES += $(MY_GAME_BACKEND_GAMEOBJECTS_WEAPONS_PATH)/CGun14Inch.cpp
LOCAL_SRC_FILES += $(MY_GAME_BACKEND_GAMEOBJECTS_WEAPONS_PATH)/CWeaponCannon20mm.cpp
LOCAL_SRC_FILES += $(MY_GAME_BACKEND_GAMEOBJECTS_WEAPONS_PATH)/CMachineGun13mm.cpp
LOCAL_SRC_FILES += $(MY_GAME_BACKEND_GAMEOBJECTS_WEAPONS_PATH)/CMachineGun8mm.cpp
LOCAL_SRC_FILES += $(MY_GAME_BACKEND_GAMEOBJECTS_WEAPONS_PATH)/CGun7Inch.cpp
LOCAL_SRC_FILES += $(MY_GAME_BACKEND_GAMEOBJECTS_WEAPONS_PATH)/CGunAA75mm.cpp
LOCAL_SRC_FILES += $(MY_GAME_BACKEND_GAMEOBJECTS_WEAPONS_PATH)/CGunAA88mm.cpp
LOCAL_SRC_FILES += $(MY_GAME_BACKEND_GAMEOBJECTS_WEAPONS_PATH)/CRifle.cpp
LOCAL_SRC_FILES += $(MY_GAME_BACKEND_GAMEOBJECTS_WEAPONS_PATH)/CShipDual75mmGun.cpp
LOCAL_SRC_FILES += $(MY_GAME_BACKEND_GAMEOBJECTS_WEAPONS_PATH)/CShipDualMachineGun.cpp
LOCAL_SRC_FILES += $(MY_GAME_BACKEND_GAMEOBJECTS_WEAPONS_PATH)/CStandardRocketWeapon.cpp
LOCAL_SRC_FILES += $(MY_GAME_BACKEND_GAMEOBJECTS_WEAPONS_PATH)/CTankAAGun.cpp
LOCAL_SRC_FILES += $(MY_GAME_BACKEND_GAMEOBJECTS_WEAPONS_PATH)/CTankGun80mm.cpp
LOCAL_SRC_FILES += $(MY_GAME_BACKEND_GAMEOBJECTS_WEAPONS_PATH)/CWeaponBomb1000Kg.cpp
LOCAL_SRC_FILES += $(MY_GAME_BACKEND_GAMEOBJECTS_WEAPONS_PATH)/CWeaponBomb100Kg.cpp
LOCAL_SRC_FILES += $(MY_GAME_BACKEND_GAMEOBJECTS_WEAPONS_PATH)/CWeaponBomb500Kg.cpp
LOCAL_SRC_FILES += $(MY_GAME_BACKEND_GAMEOBJECTS_WEAPONS_PATH)/CWeaponBombCluster.cpp
LOCAL_SRC_FILES += $(MY_GAME_BACKEND_GAMEOBJECTS_WEAPONS_PATH)/CWeaponTorpedo.cpp
LOCAL_SRC_FILES += $(MY_GAME_BACKEND_GAMEOBJECTS_WEAPONS_PATH)/CWeaponAircraftCannon20mm.cpp
LOCAL_SRC_FILES += $(MY_GAME_BACKEND_GAMEOBJECTS_WEAPONS_PATH)/CWeaponAircraftMachineGun13mm.cpp
LOCAL_SRC_FILES += $(MY_GAME_BACKEND_GAMEOBJECTS_WEAPONS_PATH)/CWeaponAircraftMachineGun8mm.cpp
LOCAL_SRC_FILES += $(MY_GAME_BACKEND_GAMEOBJECTS_WEAPONS_PATH)/CBackGunMachineGun8mm.cpp
LOCAL_SRC_FILES += $(MY_GAME_BACKEND_GAMEOBJECTS_WEAPONS_PATH)/CBackGunDoubleMachineGun8mm.cpp
LOCAL_SRC_FILES += $(MY_GAME_BACKEND_GAMEOBJECTS_WEAPONS_PATH)/CBackGunDoubleMachineGun13mm.cpp

#-------------------------------- NATIVE ------------------------------- #

#Add Native classes here:
LOCAL_SRC_FILES += $(MY_NATIVE_PATH)/CAndroidFighterPilotThePacificWar.cpp

#Utility classes
LOCAL_SRC_FILES += $(MY_NATIVE_UTILITY_PATH)/CAndroidFileStream.cpp
LOCAL_SRC_FILES += $(MY_NATIVE_UTILITY_PATH)/NativeIPC.cpp
LOCAL_SRC_FILES += $(MY_NATIVE_UTILITY_PATH)/CAndroidImageStore.cpp
LOCAL_SRC_FILES += $(MY_NATIVE_UTILITY_PATH)/CAndroidAssetDirectory.cpp
LOCAL_SRC_FILES += $(MY_NATIVE_UTILITY_PATH)/CAndroidTouchEventHandler.cpp
LOCAL_SRC_FILES += $(MY_NATIVE_UTILITY_PATH)/CAndroidSystem.cpp
LOCAL_SRC_FILES += $(MY_NATIVE_UTILITY_PATH)/CAndroidTCPConnectionEngine.cpp
LOCAL_SRC_FILES += $(MY_NATIVE_UTILITY_PATH)/CAndroidAmazonGameCircleFunctions.cpp

#Add graphic files here
LOCAL_SRC_FILES += $(MY_NATIVE_PATH)/graphic/AndroidGraphicsEngine.cpp

#-------------------------------- CORE ------------------------------- #

#Add Core classes here:
LOCAL_SRC_FILES +=  $(MY_CORE_PATH)/CGame.cpp

#Add sound files here
LOCAL_SRC_FILES += $(MY_CORE_SOUND_PATH)/CGameAudioEngine.cpp
LOCAL_SRC_FILES += $(MY_CORE_SOUND_PATH)/COpenSLEngine.cpp
LOCAL_SRC_FILES += $(MY_CORE_SOUND_PATH)/CMusicPlayer.cpp
LOCAL_SRC_FILES += $(MY_CORE_SOUND_PATH)/CSoundPlayer.cpp
LOCAL_SRC_FILES += $(MY_CORE_SOUND_PATH)/CSoundMixer.cpp
LOCAL_SRC_FILES += $(MY_CORE_SOUND_PATH)/CWavLoader.cpp
LOCAL_SRC_FILES += $(MY_CORE_SOUND_PATH)/CSoundObject.cpp
LOCAL_SRC_FILES += $(MY_CORE_SOUND_PATH)/CSoundEngine.cpp
LOCAL_SRC_FILES += $(MY_CORE_SOUND_PATH)/CSoundFileNameMapping.cpp
LOCAL_SRC_FILES += $(MY_CORE_SOUND_PATH)/CSoundFilePreferredVolume.cpp

#Add graphic classes here
LOCAL_SRC_FILES += $(MY_CORE_GRAPHICS_PATH)/CGraphicsEngine.cpp
LOCAL_SRC_FILES += $(MY_CORE_GRAPHICS_PATH)/CTextureObject.cpp
LOCAL_SRC_FILES += $(MY_CORE_GRAPHICS_PATH)/CAnimationPlayer.cpp
LOCAL_SRC_FILES += $(MY_CORE_GRAPHICS_PATH)/CGraphicsFont.cpp
LOCAL_SRC_FILES += $(MY_CORE_GRAPHICS_PATH)/COverSizedImage.cpp

#Add utility cpp files here
LOCAL_SRC_FILES += $(MY_CORE_UTILTIY_PATH)/CFileStream.cpp
LOCAL_SRC_FILES += $(MY_CORE_UTILTIY_PATH)/CImageStore.cpp
LOCAL_SRC_FILES += $(MY_CORE_UTILTIY_PATH)/CTouchEventHandler.cpp
LOCAL_SRC_FILES += $(MY_CORE_UTILTIY_PATH)/CFramesPerSecondCounter.cpp
LOCAL_SRC_FILES += $(MY_CORE_UTILTIY_PATH)/CLocalizationEngine.cpp
LOCAL_SRC_FILES += $(MY_CORE_UTILTIY_PATH)/CMemoryUsageTracker.cpp
LOCAL_SRC_FILES += $(MY_CORE_UTILTIY_PATH)/CRandomGenerator.cpp
LOCAL_SRC_FILES += $(MY_CORE_UTILTIY_PATH)/CUserStatsTrackerDaemon.cpp
LOCAL_SRC_FILES += $(MY_CORE_UTILTIY_PATH)/CTCPConnectionEngine.cpp

#Add Standard Library classes here
LOCAL_SRC_FILES += $(MY_CORE_STD_LIB_PATH)/TIntFloat.cpp
LOCAL_SRC_FILES += $(MY_CORE_STD_LIB_PATH)/TIntFloat64.cpp
LOCAL_SRC_FILES += $(MY_CORE_STD_LIB_PATH)/RectAndPoints.cpp
LOCAL_SRC_FILES += $(MY_CORE_STD_LIB_PATH)/CString.cpp
LOCAL_SRC_FILES += $(MY_CORE_STD_LIB_PATH)/CMath.cpp

#Add View cpp files here
LOCAL_SRC_FILES += $(MY_CORE_VIEWS_PATH)/CBasicView.cpp
LOCAL_SRC_FILES += $(MY_CORE_VIEWS_PATH)/CViewKeyboard.cpp

#Add Transition cpp files here
LOCAL_SRC_FILES += $(MY_CORE_TRANSITIONS_PATH)/CBasicTransition.cpp
LOCAL_SRC_FILES += $(MY_CORE_TRANSITIONS_PATH)/CTransitionWithoutEffects.cpp
LOCAL_SRC_FILES += $(MY_CORE_TRANSITIONS_PATH)/CTransitionHorizontalFlip.cpp
LOCAL_SRC_FILES += $(MY_CORE_TRANSITIONS_PATH)/CTransitionSlideAngled.cpp
LOCAL_SRC_FILES += $(MY_CORE_TRANSITIONS_PATH)/CTransitionSlideOnTop.cpp
LOCAL_SRC_FILES += $(MY_CORE_TRANSITIONS_PATH)/CTransitionHorizontalPeelOff.cpp
LOCAL_SRC_FILES += $(MY_CORE_TRANSITIONS_PATH)/CTransitionHorizontalFlippingTiles.cpp
LOCAL_SRC_FILES += $(MY_CORE_TRANSITIONS_PATH)/CTransitionOpenDoor.cpp
LOCAL_SRC_FILES += $(MY_CORE_TRANSITIONS_PATH)/CTransitionOpenDoorRotating.cpp
LOCAL_SRC_FILES += $(MY_CORE_TRANSITIONS_PATH)/CTransitionCubeRotation.cpp

#Add Components cpp files here
LOCAL_SRC_FILES += $(MY_CORE_COMPONENTS_PATH)/CBasicComponent.cpp
LOCAL_SRC_FILES += $(MY_CORE_COMPONENTS_PATH)/CButton.cpp
LOCAL_SRC_FILES += $(MY_CORE_COMPONENTS_PATH)/CRadioButton.cpp
LOCAL_SRC_FILES += $(MY_CORE_COMPONENTS_PATH)/CRadioButtonGroup.cpp
LOCAL_SRC_FILES += $(MY_CORE_COMPONENTS_PATH)/CCheckBoxButton.cpp
LOCAL_SRC_FILES += $(MY_CORE_COMPONENTS_PATH)/CTouchSurface.cpp
LOCAL_SRC_FILES += $(MY_CORE_COMPONENTS_PATH)/CScrollBar.cpp

#Add Popups cpp files here
LOCAL_SRC_FILES += $(MY_CORE_POPUPS_PATH)/CBasicPopup.cpp
LOCAL_SRC_FILES += $(MY_CORE_POPUPS_PATH)/CPopupEnterText.cpp
LOCAL_SRC_FILES += $(MY_CORE_POPUPS_PATH)/CPopupProgressBar.cpp
LOCAL_SRC_FILES += $(MY_CORE_POPUPS_PATH)/CPopupWarning.cpp

#Add Collision classes here
LOCAL_SRC_FILES += $(MY_CORE_COLLISION_PATH)/CHitBox.cpp

#Add Cryptography classes here
LOCAL_SRC_FILES += $(MY_CORE_CRYPTOGRAPHY_PATH)/CCryptographyEngima.cpp

#debug
LOCAL_SRC_FILES += test.cpp
#-------------------------------- Other Stuff ------------------------------- #

#compiler flags
LOCAL_CFLAGS    += -Werror -g -DEBUG

# for native audio
LOCAL_LDLIBS    += -lOpenSLES
LOCAL_LDLIBS    += -landroid

# for OpenGL
LOCAL_LDLIBS    += -lEGL
LOCAL_LDLIBS    += -lGLESv1_CM #OpenGL 1.0

# for logging
LOCAL_LDLIBS    += -llog



# for OpenType
LOCAL_STATIC_LIBRARIES += freetype
# for VirtualBox
#LOCAL_STATIC_LIBRARIES += gdx


include $(BUILD_SHARED_LIBRARY)

#MK for free type
include $(LOCAL_PATH)/freetype-arm-linux-androideabi/Android.mk 