/*
 * GameObjectDefaultValues.h
 *
 *  Created on: 25-Jan-2010
 *      Author: David Stoll
 *
 *      Contains all the default values for all the game objects in the Game
 */

#ifndef CGAMEOBJECTDEFAULTVALUES_H_
#define CGAMEOBJECTDEFAULTVALUES_H_

#include "includes/game/common/CGameVariables.h"

class CGameObjectDefaultValues
{

public:

	//Player
  static TInt PlayerLives;

  static TInt DauntlessHealth;
  static TInt Dauntless1000KgBombMaxLoad;
  static TInt Dauntless500KgBombMaxLoad;
  static TInt Dauntless100KgBombMaxLoad;
  static TInt DauntlessClusterBombMaxLoad;
  static TInt DauntlessRocketMaxLoad;
  static TInt DauntlessTorpedoMaxLoad;
  static TInt MitchellHealth;
  static TInt Mitchell1000KgBombMaxLoad;
  static TInt Mitchell500KgBombMaxLoad;

  static TInt ValHealth;
  static TInt Val1000KgBombMaxLoad;
  static TInt Val500KgBombMaxLoad;
  static TInt Val100KgBombMaxLoad;
  static TInt ValClusterBombMaxLoad;
  static TInt ValRocketMaxLoad;
  static TInt ValTorpedoMaxLoad;
  static TInt BettyHealth;
  static TInt Betty1000KgBombMaxLoad;
  static TInt Betty500KgBombMaxLoad;

  static TInt USSVictoryHealth;
  static TInt AmericanLCTHealth;
  static TInt AmericanCarrierHealth;
  static TInt AmericanDestroyerHealth;
  static TInt AmericanBattleshipUSSTennesseeHealth;
  static TInt AmericanTroopTransporterHealth;
  static TInt JapaneseLCTHealth;
  static TInt JapaneseCarrierHealth;
  static TInt JapaneseDestroyerHealth;
  static TInt JapaneseBattleshipYamatoHealth;
  static TInt JapaneseTroopTransporterHealth;
  static TInt JapaneseOilTankerHealth;
  static void LoadDefaultValues();

private:
  static void LoadDefaultValuesBaby();
  static void LoadDefaultValuesEasy();
  static void LoadDefaultValuesMedium();
  static void LoadDefaultValuesHard();

};


/*-------------------- About Z Values --------------------//
 *
 *	Z Values are the only thing that determines what object is drawn infront or behind another object
 *	and is therefore very important to keep them well organized for clear visusals on what is going on
 *	on the battlefield
 *
 * 	Each object will be assigned a number from a incremental list of 1 to 999, to make sure that objects
 * 	in the same category have different Z Values and don't overlap.
 * 	Also an object's Z might decreases if it gets destroyed to make things more visible for objects behind it
 *  but still keeping the beautiful sight of destored object littering the battlefield
 *
 * 	Here is a listing of the Z Values assigned to different types of objects
 *
 * 	Floor 6000
 * 	Any type of Projectile 5000
 * 	LCT and other smaller ships 4000 (since they that might pass by a bigger ship because they travel)
 * 	Small Planes 3000
 *	Big Planes 2000
 *	Big Ships 1000
 * 	Soldiers 0 (since they are so small they will rarely obscure the view of other objects)
 * 	AA-Guns -1000
 * 	Tanks -2000
 * 	Buildings -3000
 * 	Trees -4000
 *
 * 	Others -10000 (Z Value is not important since drawing is ordered is enfored directly in drawing thread)
 */

#define Z_VALUE_CATEGORY_RANGE 1000 // goes from 0 to RANGE_VALUE, is added to each new draw Object to have distinct Z Values in each category

//	Categories:


#define LANDING_SURFACE_DEFAULT_Z_VALUE 10000
#define FLOOR_DEFAULT_Z_VALUE 9000
#define SMOKE_DEFAULT_Z_VALUE 8000
#define EXPLOSION_DEFAULT_Z_VALUE 7000
#define SMALL_PLANE_DEFAULT_Z_VALUE 6000
#define BIG_PLANE_DEFAULT_Z_VALUE 5000
#define SOLDIERS_DEFAULT_Z_VALUE 4000
#define AA_GUNS_DEFAULT_Z_VALUE 3000
#define TANKS_DEFAULT_Z_VALUE 2000
#define PROJECTILE_DEFAULT_Z_VALUE 1000
#define SMALL_SHIP_DEFAULT_Z_VALUE (-10000)// we want that destroyed airplanes are still infront of alive ships, but that dead small ships are still infront of big alive ships as well
#define BIG_SHIP_DEFAULT_Z_VALUE (-21000)
#define BUILDINGS_DEFAULT_Z_VALUE (-22000)
#define TREES_DEFAULT_Z_VALUE (-23000)
#define NOT_IMPORTANT_Z_VALUE (-30000)

#define PUT_INTO_BACKGROUND_Z_VALUE (-10000) //this value is added to objects that get destroyed to put them into the background, should still be before buildings and Trees

//common to everything
#define DEFAULT_FRAMES_PER_MOVE 1
#define MIN_Y_VALUE_BEFORE_GETTING_RECYCLED -500


//----------------Aircarfts---------------------//

#define KILL_ANY_AIRPLANE_DAMAGE 1000
#define KILL_ANY_AIRPLANE_ARMOR_PENETRATION 1000

#define SMALL_AIRCRAFT_FRAMES_UNTIL_SMOKE_DISAPPEARS 40
#define BIG_AIRCRAFT_FRAMES_UNTIL_SMOKE_DISAPPEARS 80

/*--------------Baisc Aircraft----------*/
#define BASIC_AIRCRAFT_SINKING_FACTOR 1
#define BASIC_AIRCRAFT_FLYING_ANGEL_CHANGE_STEP_SIZE_SMALL 15 //since sin(15)*4>1
#define BASIC_AIRCRAFT_FLYING_ANGEL_CHANGE_STEP_SIZE 15 //since sin(15)*4>1
#define BASIC_AIRCRAFT_CHANGE_ACCElERATION_STEP_SIZE 0.5
#define BASIC_AIRCAFT_DEFAULT_FRAMES_PER_MOVE 1
#define BASIC_AIRCRAFT_MINIMUM_SPEED_TO_AVOID_FALLING 4
#define BASIC_AIRCAFT_ACCELERATION_CHANGE_DUE_TO_ANGEL 3
#define BASIC_AIRCAFT_EXTRA_DOWN_SPEED (0.25) //was 0.05
#define BASIC_AIRCARFT_ACCELERATION_TOO_FAST_TO_LAND 9
#define BASIC_AIRCRAFT_MAXIMUM_SPEED_ON_LANDING_SURFACE 6
#define BASIC_AIRCRAFT_ENGINE_SPEED_UPDATE_FACTOR (0.07)//tells us how fast the wanted speed and the current speed get adjusted, takes longer to speed up or too slow down
#define BASIC_AIRCRAFT_DIVE_SPEED_UPDATE_FACTOR (0.25)//tells us how fast the wanted speed and the current speed get adjusted, takes longer to speed up or too slow down
#define BASIC_AIRCARFT_LANDING_SURFACE_MAXIMUM_ANGEL_FROM_SURFACE 20
#define BASIC_AIRCARFT_CHANGE_ANGEL_SPEED_CHANGE_UP (-1.2)
#define BASIC_AIRCARFT_CHANGE_ANGLE_SPEED_CHANGE_DOWN (1)
#define BASIC_AIRCARFT_MAX_ACCELERATION_FACTOR 20
#define BASIC_AIRCRAFT_TURN_BASE_FACTOR 12 //one factor is 1 sec in the game. The bigger the faster all turns get, smaller all turns take longer
#define BASIC_AIRCRAFT_ANGLE_CHANGE_BASE_FACTOR 10 //one factor is 1 frame in the game
#define BASIC_AIRCRAFT_ANGLE_CHANGE_BASE_FACTOR_ADJUSTMENT (-40) // the angle change factor of the aircraft will be adjust by this value to align it properly
#define HEAVY_BOMBER_AIRCARFT_CHANGE_ANGLE_SPEED_CHANGE_DOWN 5

/*---------------US Navy Close Air Support: Dauntless-------------------*/
#define DAUNTLESS_Z_VALUE SMALL_PLANE_DEFAULT_Z_VALUE
#define DAUNTLESS_NUMBER_OF_ORIGINIAL_HITBOX_POINTS 8
#define DAUNTLESS_NUMBER_OF_PROJECTED_HITBOX_POINTS 10
#define DAUNTLESS_LANDING_GEAR_NUMBER_OF_ORIGINIAL_HITBOX_POINTS 5
#define DAUNTLESS_LANDING_GEAR_NUMBER_OF_PROJECTED_HITBOX_POINTS 7
#define DAUNTLESS_WIDTH 80
#define DAUNTLESS_HEIGHT 32
#define DAUNTLESS_CRASH_STATE_WIDTH 80
#define DAUNTLESS_CRASH_STATE_HEIGHT 19
#define DAUNTLESS_MAX_ACCELERATION 410 //should be in Km
#define DAUNTLESS_TURN_TIME_FACTOR 26 //based on realistic second value
#define DAUNTLESS_ANGLE_CHANGE_TIME_FACTOR 100 //based on realistic Climb value in seconds
#define DAUNTLESS_ARMOR 1
#define DAUNTLESS_HEALTH 290 //based on WEIGHT of plane in KG
#define DAUNTLESS_KILL_BASE_SCORE 155

#define DAUNTLESS_FRONT_13MM_MACHINE_GUN_1_POSITION_X -1
#define DAUNTLESS_FRONT_13MM_MACHINE_GUN_1_POSITION_Y 19
#define DAUNTLESS_FRONT_13MM_MACHINE_GUN_2_POSITION_X -1
#define DAUNTLESS_FRONT_13MM_MACHINE_GUN_2_POSITION_Y 15
#define DAUNTLESS_1000KG_BOMB_POSITION_X -10
#define DAUNTLESS_1000KG_BOMB_POSITION_Y -1
#define DAUNTLESS_500KG_BOMB_POSITION_X -17
#define DAUNTLESS_500KG_BOMB_POSITION_Y 1
#define DAUNTLESS_100KG_BOMB_POSITION_X -10
#define DAUNTLESS_100KG_BOMB_POSITION_Y 3
#define DAUNTLESS_CLUSTER_BOMB_POSITION_X -12
#define DAUNTLESS_CLUSTER_BOMB_POSITION_Y 1
#define DAUNTLESS_TORPEDO_POSITION_X -9
#define DAUNTLESS_TORPEDO_POSITION_Y 2
#define DAUNTLESS_STANDARD_ROCKET_POSITION_X -8
#define DAUNTLESS_STANDARD_ROCKET_POSITION_Y -1
#define DAUNTLESS_SMOKE_CREATOR_POSITION_X -35
#define DAUNTLESS_SMOKE_CREATOR_POSITION_Y 10
#define DAUNTLESS_BACK_CANNON_POSITION_X -39
#define DAUNTLESS_BACK_CANNON_POSITION_Y 23
#define DAUNTLESS_CLUSTER_BOMB_TIMER_FRAMES 45 //sets after how many frames the bomb explodes to releases its bombs

/*---------------US Navy Medium Bomber: Mitchell (B-25)-------------------*/
//basic properties
#define MITCHELL_Z_VALUE BIG_PLANE_DEFAULT_Z_VALUE
#define MITCHELL_WIDTH 340
#define MITCHELL_HEIGHT 93
#define MITCHELL_MAX_ACCELERATION 438
#define MITCHELL_TURN_TIME_FACTOR 38 //based on realistic second value
#define MITCHELL_ANGLE_CHANGE_TIME_FACTOR 110 //based on realistic Climb value in seconds
#define MITCHELL_ARMOR 1
#define MITCHELL_HEALTH 885
#define MITCHELL_KILL_BASE_SCORE 200
//for crash we have differnt width
#define MITCHELL_CRASH_STATE_WIDTH 363
#define MITCHELL_CRASH_STATE_HEIGHT 73
//weapon positions
#define MITCHELL_FRONT_CANNON_POSITION_X -7
#define MITCHELL_FRONT_CANNON_POSITION_Y 28
#define MITCHELL_TOP_CANNON_POSITION_X -130
#define MITCHELL_TOP_CANNON_POSITION_Y 72
#define MITCHELL_BACK_CANNON_POSITION_X -335
#define MITCHELL_BACK_CANNON_POSITION_Y 47
#define MITCHELL_BOTTOM_CANNON_POSITION_X -130
#define MITCHELL_BOTTOM_CANNON_POSITION_Y 4
//bombs
#define MITCHELL_MIDDLE_POSITION_OF_BOMBS 92
#define MITCHELL_FIRST_1000KG_BOMB_POSITION_X -20
#define MITCHELL_FIRST_1000KG_BOMB_POSITION_Y 15
#define MITCHELL_FIRST_500KG_BOMB_POSITION_X -70
#define MITCHELL_FIRST_500KG_BOMB_POSITION_Y 15
#define MITCHELL_SECOND_1000KG_BOMB_POSITION_X -100
#define MITCHELL_SECOND_1000KG_BOMB_POSITION_Y 15
#define MITCHELL_SECOND_500KG_BOMB_POSITION_X -150
#define MITCHELL_SECOND_500KG_BOMB_POSITION_Y 15
//some smoke creator positions
#define MITCHELL_SMOKE_CREATOR_ENGINE1_POSITION_X -110
#define MITCHELL_SMOKE_CREATOR_ENGINE1_POSITION_Y 33
#define MITCHELL_SMOKE_CREATOR_ENGINE2_POSITION_X -150
#define MITCHELL_SMOKE_CREATOR_ENGINE2_POSITION_Y 33

/*---------------Imperial Japanese Dive Bomber: Val(Aichi D3A) -------------------*/
#define VAL_Z_VALUE SMALL_PLANE_DEFAULT_Z_VALUE
#define VAL_NUMBER_OF_ORIGINIAL_HITBOX_POINTS 8
#define VAL_NUMBER_OF_PROJECTED_HITBOX_POINTS 10
#define VAL_LANDING_GEAR_NUMBER_OF_ORIGINIAL_HITBOX_POINTS 5
#define VAL_LANDING_GEAR_NUMBER_OF_PROJECTED_HITBOX_POINTS 7
#define VAL_WIDTH 85
#define VAL_HEIGHT 32
#define VAL_CRASH_STATE_WIDTH 85
#define VAL_CRASH_STATE_HEIGHT 19
#define VAL_MAX_ACCELERATION 430
#define VAL_TURN_TIME_FACTOR 30 //based on realistic second value
#define VAL_ANGLE_CHANGE_TIME_FACTOR 65 //based on realistic Climb value in seconds
#define VAL_ARMOR 1 //was 1 before, set to high value to debug sounds
#define VAL_HEALTH 240 //based on WEIGHT of plane in KG
#define VAL_KILL_BASE_SCORE 155


#define VAL_FRONT_8MM_MACHINE_GUN_1_POSITION_X -4
#define VAL_FRONT_8MM_MACHINE_GUN_1_POSITION_Y 18
#define VAL_FRONT_8MM_MACHINE_GUN_2_POSITION_X -4
#define VAL_FRONT_8MM_MACHINE_GUN_2_POSITION_Y 14
#define VAL_1000KG_BOMB_POSITION_X -10
#define VAL_1000KG_BOMB_POSITION_Y -2
#define VAL_500KG_BOMB_POSITION_X -17
#define VAL_500KG_BOMB_POSITION_Y 0
#define VAL_100KG_BOMB_POSITION_X -10
#define VAL_100KG_BOMB_POSITION_Y 2
#define VAL_CLUSTER_BOMB_POSITION_X -12
#define VAL_CLUSTER_BOMB_POSITION_Y 0
#define VAL_TORPEDO_POSITION_X -9
#define VAL_TORPEDO_POSITION_Y 1
#define VAL_STANDARD_ROCKET_POSITION_X -10
#define VAL_STANDARD_ROCKET_POSITION_Y -3
#define VAL_SMOKE_CREATOR_POSITION_X -35
#define VAL_SMOKE_CREATOR_POSITION_Y 10
#define VAL_BACK_CANNON_POSITION_X -39
#define VAL_BACK_CANNON_POSITION_Y 22
#define VAL_CLUSTER_BOMB_TIMER_FRAMES 45 //sets after how many frames the bomb explodes to releases its bombs

/*---------------Imperial Japanese Navy Bomber: Betty(Mitsubishi G4M1)-------------------*/
//basic properties
#define BETTY_Z_VALUE BIG_PLANE_DEFAULT_Z_VALUE
#define BETTY_WIDTH 340
#define BETTY_HEIGHT 98
#define BETTY_MAX_ACCELERATION 435
#define BETTY_TURN_TIME_FACTOR 25 //based on realistic second value
#define BETTY_ANGLE_CHANGE_TIME_FACTOR 100 //based on realistic Climb value in seconds
#define BETTY_ARMOR 1
#define BETTY_HEALTH 674
#define BETTY_KILL_BASE_SCORE 200
//for crash we have differnt width
#define BETTY_CRASH_STATE_WIDTH 340
#define BETTY_CRASH_STATE_HEIGHT 70
//weapon positions
#define BETTY_FRONT_CANNON_POSITION_X -4
#define BETTY_FRONT_CANNON_POSITION_Y 31
#define BETTY_TOP_CANNON_POSITION_X -161
#define BETTY_TOP_CANNON_POSITION_Y 60
#define BETTY_BACK_CANNON_POSITION_X -336
#define BETTY_BACK_CANNON_POSITION_Y 29
#define BETTY_BOTTOM_CANNON_POSITION_X -161
#define BETTY_BOTTOM_CANNON_POSITION_Y 6
//bombs
#define BETTY_MIDDLE_POSITION_OF_BOMBS 140
#define BETTY_FIRST_1000KG_BOMB_POSITION_X -80
#define BETTY_FIRST_1000KG_BOMB_POSITION_Y 11
#define BETTY_FIRST_500KG_BOMB_POSITION_X -135
#define BETTY_FIRST_500KG_BOMB_POSITION_Y 11
#define BETTY_SECOND_1000KG_BOMB_POSITION_X -165
#define BETTY_SECOND_1000KG_BOMB_POSITION_Y 11
#define BETTY_SECOND_500KG_BOMB_POSITION_X -220
#define BETTY_SECOND_500KG_BOMB_POSITION_Y 11
//some smoke creator positions
#define BETTY_SMONE_CREATOR_ENGINE1_POSITION_X -80
#define BETTY_SMONE_CREATOR_ENGINE1_POSITION_Y 28
#define BETTY_SMONE_CREATOR_ENGINE2_POSITION_X -140
#define BETTY_SMONE_CREATOR_ENGINE2_POSITION_Y 43

//-------------------------- SHIPS -----------------------//
#define SHIP_BASIC_SINKING_SEQUENCE_INCREASE_Y (0.2)
#define SHIP_BASIC_SPEED (0.3)
#define TROOPTRANSPORTER_FRAMES_UNTIL_LCT_SPAWN  (GFRAMES_PER_SECOND_BACKEND * 60 * 4) //every 4 mins
#define CARRIER_DEFAULT_NUMBER_OF_AIRCRAFTS 10
#define CARRIER_DEFAULT_SECS_UNTIL_SPAWN_AIRCRAFT (GFRAMES_PER_SECOND_BACKEND * 60 * 2) //every 2 mins,
#define AIRPORT_DEFAULT_SECS_UNTIL_SPAWN_AIRCRAFT (GFRAMES_PER_SECOND_BACKEND * 60 * 3) //every 3 mins,  for airport
#define CARRIER_DEFAULT_EXTRA_SPAWN_TIME_MULTIPLIER_IF_NO_PLANES_LEFT 3
#define CARRIER_KILL_BASE_SCORE 4000
#define DESTROYER_KILL_BASE_SCORE 1500
#define TROOP_TRANSPORTER_KILL_BASE_SCORE 1000
#define OIL_TANKER_KILL_BASE_SCORE 750


/*------------------- Carrier: USS Vitory -----------------------*/
#define USS_VICTORY_Z BIG_SHIP_DEFAULT_Z_VALUE
#define USS_VICTORY_NUMBER_OF_ORIGINIAL_HITBOX_POINTS 7
#define USS_VICTORY_NUMBER_OF_PROJECTED_HITBOX_POINTS 7
#define USS_VICTORY_ARMOUR 40
#define USS_VICTORY_WIDTH 1024
#define USS_VICTORY_HEIGHT 128
#define USS_VICTORY_KEEL_DEPTH 20 //was 20
#define USS_VICTORY_LANDING_SURFACE_HEIGHT 5
#define USS_VICTORY_LANDING_SURFACE_WIDTH 1024
#define USS_VICTORY_LANDING_SURFACE_HEIGHT_OFF_SET 61
#define USS_VICTORY_FLAG_POLE_X_OFFSET 600
#define USS_VICTORY_FLAG_POLE_Y_OFFSET 20
#define USS_VICTORY_AIRPLANE_POSITION_X_OFFSET 720
#define USS_VICTORY_LEFT_SMOKE_CREATOR_X_OFFSET -60
#define USS_VICTORY_LEFT_SMOKE_CREATOR_Y_OFFSET 58
#define USS_VICTORY_MIDDLE_SMOKE_CREATOR_X_OFFSET -400
#define USS_VICTORY_MIDDLE_SMOKE_CREATOR_Y_OFFSET 58
#define USS_VICTORY_RIGHT_SMOKE_CREATOR_X_OFFSET -900
#define USS_VICTORY_RIGHT_SMOKE_CREATOR_Y_OFFSET 58
#define USS_VICTORY_TOP_SMOKE_CREATOR_X_OFFSET -390
#define USS_VICTORY_TOP_SMOKE_CREATOR_Y_OFFSET 105
#define USS_VICTORY_KILL_BASE_SCORE 6000

/*------------------- American LCT -----------------------*/
#define AMERICAN_LCT_Z SMALL_SHIP_DEFAULT_Z_VALUE
#define AMERICAN_LCT_NUMBER_OF_ORIGINIAL_HITBOX_POINTS 8
#define AMERICAN_LCT_NUMBER_OF_PROJECTED_HITBOX_POINTS 8
#define AMERICAN_LCT_ARMOUR 5
#define AMERICAN_LCT_WIDTH 256
#define AMERICAN_LCT_HEIGHT 128
#define AMERICAN_LCT_KEEL_DEPTH 18
#define AMERICAN_LCT_X_UNLOAD_SAFETY_MARGIN 50
#define AMERICAN_LCT_SMOKE_CREATOR_X_OFFSET -185
#define AMERICAN_LCT_SMOKE_CREATOR_Y_OFFSET 50
#define AMERICAN_LCT_DUAL_MACHINE_GUN_X_LOCATION 185
#define AMERICAN_LCT_DUAL_MACHINE_GUN_Y_LOCATION 68
#define AMERICAN_LCT_KILL_BASE_SCORE_LOADED 500
#define AMERICAN_LCT_KILL_BASE_SCORE_EMPTY 150
#define AMERICAN_LCT_DEFAULT_SPEED (2)

/*------------------- Carrier: American Lexington -----------------------*/
#define AMERICAN_CARRIER_LEXINGTON_Z BIG_SHIP_DEFAULT_Z_VALUE
#define AMERICAN_CARRIER_LEXINGTON_NUMBER_OF_ORIGINIAL_HITBOX_POINTS 7
#define AMERICAN_CARRIER_LEXINGTON_NUMBER_OF_PROJECTED_HITBOX_POINTS 7
#define AMERICAN_CARRIER_LEXINGTON_ARMOUR 40
#define AMERICAN_CARRIER_LEXINGTON_WIDTH 1024
#define AMERICAN_CARRIER_LEXINGTON_HEIGHT 128
#define AMERICAN_CARRIER_LEXINGTON_KEEL_DEPTH 8
#define AMERICAN_CARRIER_LEXINGTON_LANDING_SURFACE_HEIGHT 5
#define AMERICAN_CARRIER_LEXINGTON_LANDING_SURFACE_WIDTH 1015
#define AMERICAN_CARRIER_LEXINGTON_LANDING_SURFACE_HEIGHT_OFF_SET 38
#define AMERICAN_CARRIER_LEXINGTON_FLAG_POLE_X_OFFSET 800
#define AMERICAN_CARRIER_LEXINGTON_FLAG_POLE_Y_OFFSET -6
#define AMERICAN_CARRIER_LEXINGTON_AIRPLANE_POSITION_X_OFFSET 500
#define AMERICAN_CARRIER_LEXINGTON_LEFT_SMOKE_CREATOR_X_OFFSET -200
#define AMERICAN_CARRIER_LEXINGTON_LEFT_SMOKE_CREATOR_Y_OFFSET 28
#define AMERICAN_CARRIER_LEXINGTON_MIDDLE_SMOKE_CREATOR_X_OFFSET -500
#define AMERICAN_CARRIER_LEXINGTON_MIDDLE_SMOKE_CREATOR_Y_OFFSET 28
#define AMERICAN_CARRIER_LEXINGTON_RIGHT_SMOKE_CREATOR_X_OFFSET -800
#define AMERICAN_CARRIER_LEXINGTON_RIGHT_SMOKE_CREATOR_Y_OFFSET 28
#define AMERICAN_CARRIER_LEXINGTON_TOP_SMOKE_CREATOR_X_OFFSET -580
#define AMERICAN_CARRIER_LEXINGTON_TOP_SMOKE_CREATOR_Y_OFFSET 88

/*------------------- American Destroyer -----------------------*/
#define AMERICAN_DESTROYER_Z SMALL_SHIP_DEFAULT_Z_VALUE
#define AMERICAN_DESTROYER_NUMBER_OF_ORIGINIAL_HITBOX_POINTS 20
#define AMERICAN_DESTROYER_NUMBER_OF_PROJECTED_HITBOX_POINTS 20
#define AMERICAN_DESTROYER_ARMOUR 40
#define AMERICAN_DESTROYER_WIDTH 512
#define AMERICAN_DESTROYER_HEIGHT 128
#define AMERICAN_DESTROYER_KEEL_DEPTH 7
#define AMERICAN_DESTROYER_LEFT_SMOKE_CREATOR_X_OFFSET -50
#define AMERICAN_DESTROYER_LEFT_SMOKE_CREATOR_Y_OFFSET 48
#define AMERICAN_DESTROYER_MIDDLE_SMOKE_CREATOR_X_OFFSET -250
#define AMERICAN_DESTROYER_MIDDLE_SMOKE_CREATOR_Y_OFFSET 48
#define AMERICAN_DESTROYER_RIGHT_SMOKE_CREATOR_X_OFFSET -450
#define AMERICAN_DESTROYER_RIGHT_SMOKE_CREATOR_Y_OFFSET 48
#define AMERICAN_DESTROYER_7_INCH_GUN_X_LOCATION 25
#define AMERICAN_DESTROYER_7_INCH_GUN_Y_LOCATION 34
#define AMERICAN_DESTROYER_NUMBER_OF_MUZZELES_PER_7_INCH_TURRENT 2
#define AMERICAN_DESTROYER_DUAL_75MM_GUN_FRONT_X_LOCATION 350
#define AMERICAN_DESTROYER_DUAL_75MM_GUN_FRONT_Y_LOCATION 45
#define AMERICAN_DESTROYER_DUAL_MACHINE_GUN_FRONT_X_LOCATION 90
#define AMERICAN_DESTROYER_DUAL_MACHINE_GUN_FRONT_Y_LOCATION 34
#define AMERICAN_DESTROYER_DUAL_MACHINE_GUN_BACK_1_X_LOCATION 437
#define AMERICAN_DESTROYER_DUAL_MACHINE_GUN_BACK_1_Y_LOCATION 27
#define AMERICAN_DESTROYER_DUAL_MACHINE_GUN_BACK_2_X_LOCATION 472
#define AMERICAN_DESTROYER_DUAL_MACHINE_GUN_BACK_2_Y_LOCATION 27

/*------------------- American Battleship USS TENNESSEE -----------------------*/
#define AMERICAN_BATTLESHIP_USS_TENNESSEE_Z SMALL_SHIP_DEFAULT_Z_VALUE
#define AMERICAN_BATTLESHIP_USS_TENNESSEE_NUMBER_OF_ORIGINIAL_HITBOX_POINTS 17
#define AMERICAN_BATTLESHIP_USS_TENNESSEE_NUMBER_OF_PROJECTED_HITBOX_POINTS 17
#define AMERICAN_BATTLESHIP_USS_TENNESSEE_ARMOUR 40
#define AMERICAN_BATTLESHIP_USS_TENNESSEE_WIDTH 1024
#define AMERICAN_BATTLESHIP_USS_TENNESSEE_HEIGHT 128
#define AMERICAN_BATTLESHIP_USS_TENNESSEE_KEEL_DEPTH 12
#define AMERICAN_BATTLESHIP_USS_TENNESSEE_LEFT_SMOKE_CREATOR_X_OFFSET -50
#define AMERICAN_BATTLESHIP_USS_TENNESSEE_LEFT_SMOKE_CREATOR_Y_OFFSET 48
#define AMERICAN_BATTLESHIP_USS_TENNESSEE_MIDDLE_SMOKE_CREATOR_X_OFFSET -250
#define AMERICAN_BATTLESHIP_USS_TENNESSEE_MIDDLE_SMOKE_CREATOR_Y_OFFSET 48
#define AMERICAN_BATTLESHIP_USS_TENNESSEE_RIGHT_SMOKE_CREATOR_X_OFFSET -450
#define AMERICAN_BATTLESHIP_USS_TENNESSEE_RIGHT_SMOKE_CREATOR_Y_OFFSET 48
//FLAG
#define AMERICAN_BATTLESHIP_USS_TENNESSEE_FLAG_X_LOCATION 620
#define AMERICAN_BATTLESHIP_USS_TENNESSEE_FLAG_Y_LOCATION 68
//SMOKE CREATOR
#define AMERICAN_BATTLESHIP_USS_TENNESSEE_SMOKE_CREATOR_LEFT_X_LOCATION -200
#define AMERICAN_BATTLESHIP_USS_TENNESSEE_SMOKE_CREATOR_LEFT_Y_LOCATION 40
#define AMERICAN_BATTLESHIP_USS_TENNESSEE_SMOKE_CREATOR_MIDDLE_X_LOCATION -550
#define AMERICAN_BATTLESHIP_USS_TENNESSEE_SMOKE_CREATOR_MIDDLE_Y_LOCATION 40
#define AMERICAN_BATTLESHIP_USS_TENNESSEE_SMOKE_CREATOR_RIGHT_X_LOCATION -900
#define AMERICAN_BATTLESHIP_USS_TENNESSEE_SMOKE_CREATOR_RIGHT_Y_LOCATION 40
//14 INCH
#define AMERICAN_BATTLESHIP_USS_TENNESSEE_NUMBER_OF_MUZZELES_PER_14_INCH_TURRENT 2
#define AMERICAN_BATTLESHIP_USS_TENNESSEE_14_INCH_FRONT_GUN_X_LOCATION 300
#define AMERICAN_BATTLESHIP_USS_TENNESSEE_14_INCH_FRONT_GUN_Y_LOCATION 66
#define AMERICAN_BATTLESHIP_USS_TENNESSEE_14_INCH_TOP_FRONT_GUN_X_LOCATION 450
#define AMERICAN_BATTLESHIP_USS_TENNESSEE_14_INCH_TOP_FRONT_GUN_Y_LOCATION 86
//MACHINE GUNS
#define AMERICAN_BATTLESHIP_USS_TENNESSEE_DUAL_MACHINE_GUN_FRONT_1_X_LOCATION 10
#define AMERICAN_BATTLESHIP_USS_TENNESSEE_DUAL_MACHINE_GUN_FRONT_1_Y_LOCATION 50
#define AMERICAN_BATTLESHIP_USS_TENNESSEE_DUAL_MACHINE_GUN_FRONT_2_X_LOCATION 50
#define AMERICAN_BATTLESHIP_USS_TENNESSEE_DUAL_MACHINE_GUN_FRONT_2_Y_LOCATION 50
#define AMERICAN_BATTLESHIP_USS_TENNESSEE_DUAL_MACHINE_GUN_FRONT_3_X_LOCATION 170
#define AMERICAN_BATTLESHIP_USS_TENNESSEE_DUAL_MACHINE_GUN_FRONT_3_Y_LOCATION 50
#define AMERICAN_BATTLESHIP_USS_TENNESSEE_DUAL_MACHINE_GUN_TOP_X_LOCATION 670
#define AMERICAN_BATTLESHIP_USS_TENNESSEE_DUAL_MACHINE_GUN_TOP_Y_LOCATION 70
#define AMERICAN_BATTLESHIP_USS_TENNESSEE_DUAL_MACHINE_GUN_BACK_1_X_LOCATION 720
#define AMERICAN_BATTLESHIP_USS_TENNESSEE_DUAL_MACHINE_GUN_BACK_1_Y_LOCATION 60
#define AMERICAN_BATTLESHIP_USS_TENNESSEE_DUAL_MACHINE_GUN_BACK_2_X_LOCATION 940
#define AMERICAN_BATTLESHIP_USS_TENNESSEE_DUAL_MACHINE_GUN_BACK_2_Y_LOCATION 38
#define AMERICAN_BATTLESHIP_USS_TENNESSEE_DUAL_MACHINE_GUN_BACK_3_X_LOCATION 980
#define AMERICAN_BATTLESHIP_USS_TENNESSEE_DUAL_MACHINE_GUN_BACK_3_Y_LOCATION 38
//75 MM
#define AMERICAN_BATTLESHIP_USS_TENNESSEE_75MM_GUN_FRONT_X_LOCATION 90
#define AMERICAN_BATTLESHIP_USS_TENNESSEE_75MM_GUN_FRONT_Y_LOCATION 60
#define AMERICAN_BATTLESHIP_USS_TENNESSEE_75MM_GUN_TOP_X_LOCATION 770
#define AMERICAN_BATTLESHIP_USS_TENNESSEE_75MM_GUN_TOP_Y_LOCATION 70
#define AMERICAN_BATTLESHIP_USS_TENNESSEE_75MM_GUN_BACK_X_LOCATION 870
#define AMERICAN_BATTLESHIP_USS_TENNESSEE_75MM_GUN_BACK_Y_LOCATION 46
#define AMERICAN_BATTLESHIP_USS_TENNESSEE_KILL_BASE_SCORE 5000

/*------------------- American Troop Transporter -----------------------*/
#define AMERICAN_TROOP_TRANSPORTER_Z BIG_SHIP_DEFAULT_Z_VALUE
#define AMERICAN_TROOP_TRANSPORTER_NUMBER_OF_ORIGINIAL_HITBOX_POINTS 10
#define AMERICAN_TROOP_TRANSPORTER_NUMBER_OF_PROJECTED_HITBOX_POINTS 10
#define AMERICAN_TROOP_TRANSPORTER_ARMOUR 40
#define AMERICAN_TROOP_TRANSPORTER_WIDTH 512
#define AMERICAN_TROOP_TRANSPORTER_HEIGHT 128
#define AMERICAN_TROOP_TRANSPORTER_KEEL_DEPTH 6
#define AMERICAN_TROOP_TRANSPORTER_LEFT_SMOKE_CREATOR_X_OFFSET -80
#define AMERICAN_TROOP_TRANSPORTER_LEFT_SMOKE_CREATOR_Y_OFFSET 28
#define AMERICAN_TROOP_TRANSPORTER_MIDDLE_SMOKE_CREATOR_X_OFFSET -250
#define AMERICAN_TROOP_TRANSPORTER_MIDDLE_SMOKE_CREATOR_Y_OFFSET 28
#define AMERICAN_TROOP_TRANSPORTER_RIGHT_SMOKE_CREATOR_X_OFFSET -430
#define AMERICAN_TROOP_TRANSPORTER_RIGHT_SMOKE_CREATOR_Y_OFFSET 28
#define AMERICAN_TROOP_TRANSPORTER_DUAL_MACHINE_GUN_FRONT_X_LOCATION 130
#define AMERICAN_TROOP_TRANSPORTER_DUAL_MACHINE_GUN_FRONT_Y_LOCATION 58
#define AMERICAN_TROOP_TRANSPORTER_DUAL_MACHINE_GUN_BACK_X_LOCATION 380
#define AMERICAN_TROOP_TRANSPORTER_DUAL_MACHINE_GUN_BACK_Y_LOCATION 58

/*------------------- JAPANESE LCT -----------------------*/
#define JAPANESE_LCT_Z SMALL_SHIP_DEFAULT_Z_VALUE
#define JAPANESE_LCT_NUMBER_OF_ORIGINIAL_HITBOX_POINTS 8
#define JAPANESE_LCT_NUMBER_OF_PROJECTED_HITBOX_POINTS 8
#define JAPANESE_LCT_ARMOUR 5
#define JAPANESE_LCT_WIDTH 256
#define JAPANESE_LCT_HEIGHT 128
#define JAPANESE_LCT_KEEL_DEPTH 18
#define JAPANESE_LCT_X_UNLOAD_SAFETY_MARGIN 50
#define JAPANESE_LCT_SMOKE_CREATOR_X_OFFSET -185
#define JAPANESE_LCT_SMOKE_CREATOR_Y_OFFSET 50
#define JAPANESE_LCT_DUAL_MACHINE_GUN_X_LOCATION 185
#define JAPANESE_LCT_DUAL_MACHINE_GUN_Y_LOCATION 68
#define JAPANESE_LCT_KILL_BASE_SCORE_LOADED 500
#define JAPANESE_LCT_KILL_BASE_SCORE_EMPTY 150
#define JAPANESE_LCT_DEFAULT_SPEED (2)

/*------------------- Carrier: Japanese Shoho -----------------------*/
#define JAPANESE_CARRIER_SHOHO_Z BIG_SHIP_DEFAULT_Z_VALUE
#define JAPANESE_CARRIER_SHOHO_NUMBER_OF_ORIGINIAL_HITBOX_POINTS 11
#define JAPANESE_CARRIER_SHOHO_NUMBER_OF_PROJECTED_HITBOX_POINTS 11
#define JAPANESE_CARRIER_SHOHO_ARMOUR 40
#define JAPANESE_CARRIER_SHOHO_WIDTH 1024
#define JAPANESE_CARRIER_SHOHO_HEIGHT 128
#define JAPANESE_CARRIER_SHOHO_KEEL_DEPTH 20
#define JAPANESE_CARRIER_SHOHO_LANDING_SURFACE_HEIGHT 5
#define JAPANESE_CARRIER_SHOHO_LANDING_SURFACE_WIDTH 908
#define JAPANESE_CARRIER_SHOHO_LANDING_SURFACE_HEIGHT_OFF_SET 91
#define JAPANESE_CARRIER_SHOHO_FLAG_POLE_X_OFFSET 500
#define JAPANESE_CARRIER_SHOHO_FLAG_POLE_Y_OFFSET 50
#define JAPANESE_CARRIER_SHOHO_AIRPLANE_POSITION_X_OFFSET 500
#define JAPANESE_CARRIER_SHOHO_LEFT_SMOKE_CREATOR_X_OFFSET -230
#define JAPANESE_CARRIER_SHOHO_LEFT_SMOKE_CREATOR_Y_OFFSET 48
#define JAPANESE_CARRIER_SHOHO_MIDDLE_SMOKE_CREATOR_X_OFFSET -420
#define JAPANESE_CARRIER_SHOHO_MIDDLE_SMOKE_CREATOR_Y_OFFSET 48
#define JAPANESE_CARRIER_SHOHO_RIGHT_SMOKE_CREATOR_X_OFFSET -640
#define JAPANESE_CARRIER_SHOHO_RIGHT_SMOKE_CREATOR_Y_OFFSET 48
#define JAPANESE_CARRIER_SHOHO_BOTTOM_RIGHT_SMOKE_CREATOR_X_OFFSET -960
#define JAPANESE_CARRIER_SHOHO_BOTTOM_RIGHT_SMOKE_CREATOR_Y_OFFSET 38

/*------------------- Carrier: Japanese Shokaku -----------------------*/
#define JAPANESE_CARRIER_SHOKAKU_Z BIG_SHIP_DEFAULT_Z_VALUE
#define JAPANESE_CARRIER_SHOKAKU_NUMBER_OF_ORIGINIAL_HITBOX_POINTS 9
#define JAPANESE_CARRIER_SHOKAKU_NUMBER_OF_PROJECTED_HITBOX_POINTS 9
#define JAPANESE_CARRIER_SHOKAKU_ARMOUR 40
#define JAPANESE_CARRIER_SHOKAKU_WIDTH 1024
#define JAPANESE_CARRIER_SHOKAKU_HEIGHT 128
#define JAPANESE_CARRIER_SHOKAKU_KEEL_DEPTH 13
#define JAPANESE_CARRIER_SHOKAKU_LANDING_SURFACE_HEIGHT 5
#define JAPANESE_CARRIER_SHOKAKU_LANDING_SURFACE_WIDTH 1017
#define JAPANESE_CARRIER_SHOKAKU_LANDING_SURFACE_HEIGHT_OFF_SET 83
#define JAPANESE_CARRIER_SHOKAKU_FLAG_POLE_X_OFFSET 530
#define JAPANESE_CARRIER_SHOKAKU_FLAG_POLE_Y_OFFSET 30
#define JAPANESE_CARRIER_SHOKAKU_AIRPLANE_POSITION_X_OFFSET 500
#define JAPANESE_CARRIER_SHOKAKU_LEFT_SMOKE_CREATOR_X_OFFSET -150
#define JAPANESE_CARRIER_SHOKAKU_LEFT_SMOKE_CREATOR_Y_OFFSET 48
#define JAPANESE_CARRIER_SHOKAKU_MIDDLE_SMOKE_CREATOR_X_OFFSET -500
#define JAPANESE_CARRIER_SHOKAKU_MIDDLE_SMOKE_CREATOR_Y_OFFSET 48
#define JAPANESE_CARRIER_SHOKAKU_RIGHT_SMOKE_CREATOR_X_OFFSET -900
#define JAPANESE_CARRIER_SHOKAKU_RIGHT_SMOKE_CREATOR_Y_OFFSET 48
#define JAPANESE_CARRIER_SHOKAKU_TOP_SMOKE_CREATOR_X_OFFSET -380
#define JAPANESE_CARRIER_SHOKAKU_TOP_SMOKE_CREATOR_Y_OFFSET 93

/*------------------- Carrier: Japanese TAIHO -----------------------*/
#define JAPANESE_CARRIER_TAIHO_Z BIG_SHIP_DEFAULT_Z_VALUE
#define JAPANESE_CARRIER_TAIHO_NUMBER_OF_ORIGINIAL_HITBOX_POINTS 9
#define JAPANESE_CARRIER_TAIHO_NUMBER_OF_PROJECTED_HITBOX_POINTS 9
#define JAPANESE_CARRIER_TAIHO_ARMOUR 40
#define JAPANESE_CARRIER_TAIHO_WIDTH 1024
#define JAPANESE_CARRIER_TAIHO_HEIGHT 128
#define JAPANESE_CARRIER_TAIHO_KEEL_DEPTH 12
#define JAPANESE_CARRIER_TAIHO_LANDING_SURFACE_HEIGHT 5
#define JAPANESE_CARRIER_TAIHO_LANDING_SURFACE_WIDTH 1017
#define JAPANESE_CARRIER_TAIHO_LANDING_SURFACE_HEIGHT_OFF_SET 71
#define JAPANESE_CARRIER_TAIHO_FLAG_POLE_X_OFFSET 542
#define JAPANESE_CARRIER_TAIHO_FLAG_POLE_Y_OFFSET 60
#define JAPANESE_CARRIER_TAIHO_AIRPLANE_POSITION_X_OFFSET 500
#define JAPANESE_CARRIER_TAIHO_LEFT_SMOKE_CREATOR_X_OFFSET -150
#define JAPANESE_CARRIER_TAIHO_LEFT_SMOKE_CREATOR_Y_OFFSET 38
#define JAPANESE_CARRIER_TAIHO_MIDDLE_SMOKE_CREATOR_X_OFFSET -545
#define JAPANESE_CARRIER_TAIHO_MIDDLE_SMOKE_CREATOR_Y_OFFSET 38
#define JAPANESE_CARRIER_TAIHO_RIGHT_SMOKE_CREATOR_X_OFFSET -900
#define JAPANESE_CARRIER_TAIHO_RIGHT_SMOKE_CREATOR_Y_OFFSET 38
#define JAPANESE_CARRIER_TAIHO_TOP_SMOKE_CREATOR_X_OFFSET -480
#define JAPANESE_CARRIER_TAIHO_TOP_SMOKE_CREATOR_Y_OFFSET 98

/*------------------- Japanese Destroyer -----------------------*/
#define JAPANESE_DESTROYER_Z SMALL_SHIP_DEFAULT_Z_VALUE
#define JAPANESE_DESTROYER_NUMBER_OF_ORIGINIAL_HITBOX_POINTS 20
#define JAPANESE_DESTROYER_NUMBER_OF_PROJECTED_HITBOX_POINTS 20
#define JAPANESE_DESTROYER_ARMOUR 40
#define JAPANESE_DESTROYER_WIDTH 512
#define JAPANESE_DESTROYER_HEIGHT 128
#define JAPANESE_DESTROYER_KEEL_DEPTH 7
#define JAPANESE_DESTROYER_LEFT_SMOKE_CREATOR_X_OFFSET -50
#define JAPANESE_DESTROYER_LEFT_SMOKE_CREATOR_Y_OFFSET 48
#define JAPANESE_DESTROYER_MIDDLE_SMOKE_CREATOR_X_OFFSET -250
#define JAPANESE_DESTROYER_MIDDLE_SMOKE_CREATOR_Y_OFFSET 48
#define JAPANESE_DESTROYER_RIGHT_SMOKE_CREATOR_X_OFFSET -450
#define JAPANESE_DESTROYER_RIGHT_SMOKE_CREATOR_Y_OFFSET 48
#define JAPANESE_DESTROYER_7_INCH_GUN_X_LOCATION 25
#define JAPANESE_DESTROYER_7_INCH_GUN_Y_LOCATION 34
#define JAPANESE_DESTROYER_NUMBER_OF_MUZZELES_PER_7_INCH_TURRENT 2
#define JAPANESE_DESTROYER_DUAL_75MM_GUN_FRONT_X_LOCATION 350
#define JAPANESE_DESTROYER_DUAL_75MM_GUN_FRONT_Y_LOCATION 45
#define JAPANESE_DESTROYER_DUAL_MACHINE_GUN_FRONT_X_LOCATION 90
#define JAPANESE_DESTROYER_DUAL_MACHINE_GUN_FRONT_Y_LOCATION 34
#define JAPANESE_DESTROYER_DUAL_MACHINE_GUN_BACK_1_X_LOCATION 437
#define JAPANESE_DESTROYER_DUAL_MACHINE_GUN_BACK_1_Y_LOCATION 27
#define JAPANESE_DESTROYER_DUAL_MACHINE_GUN_BACK_2_X_LOCATION 472
#define JAPANESE_DESTROYER_DUAL_MACHINE_GUN_BACK_2_Y_LOCATION 27

/*------------------- American Battleship USS TENNESSEE -----------------------*/
#define JAPANESE_BATTLESHIP_YAMATO_Z SMALL_SHIP_DEFAULT_Z_VALUE
#define JAPANESE_BATTLESHIP_YAMATO_NUMBER_OF_ORIGINIAL_HITBOX_POINTS 24
#define JAPANESE_BATTLESHIP_YAMATO_NUMBER_OF_PROJECTED_HITBOX_POINTS 24
#define JAPANESE_BATTLESHIP_YAMATO_ARMOUR 40
#define JAPANESE_BATTLESHIP_YAMATO_WIDTH 1024
#define JAPANESE_BATTLESHIP_YAMATO_HEIGHT 160
#define JAPANESE_BATTLESHIP_YAMATO_KEEL_DEPTH 22
#define JAPANESE_BATTLESHIP_YAMATO_LEFT_SMOKE_CREATOR_X_OFFSET -50
#define JAPANESE_BATTLESHIP_YAMATO_LEFT_SMOKE_CREATOR_Y_OFFSET 48
#define JAPANESE_BATTLESHIP_YAMATO_MIDDLE_SMOKE_CREATOR_X_OFFSET -250
#define JAPANESE_BATTLESHIP_YAMATO_MIDDLE_SMOKE_CREATOR_Y_OFFSET 48
#define JAPANESE_BATTLESHIP_YAMATO_RIGHT_SMOKE_CREATOR_X_OFFSET -450
#define JAPANESE_BATTLESHIP_YAMATO_RIGHT_SMOKE_CREATOR_Y_OFFSET 48
//FLAG
#define JAPANESE_BATTLESHIP_YAMATO_FLAG_X_LOCATION 680
#define JAPANESE_BATTLESHIP_YAMATO_FLAG_Y_LOCATION 100
//SMOKE CREATOR
#define JAPANESE_BATTLESHIP_YAMATO_SMOKE_CREATOR_LEFT_X_LOCATION -100
#define JAPANESE_BATTLESHIP_YAMATO_SMOKE_CREATOR_LEFT_Y_LOCATION 35
#define JAPANESE_BATTLESHIP_YAMATO_SMOKE_CREATOR_MIDDLE_X_LOCATION -550
#define JAPANESE_BATTLESHIP_YAMATO_SMOKE_CREATOR_MIDDLE_Y_LOCATION 35
#define JAPANESE_BATTLESHIP_YAMATO_SMOKE_CREATOR_TOP_MIDDLE_X_LOCATION -650
#define JAPANESE_BATTLESHIP_YAMATO_SMOKE_CREATOR_TOP_MIDDLE_Y_LOCATION 120
#define JAPANESE_BATTLESHIP_YAMATO_SMOKE_CREATOR_RIGHT_X_LOCATION -900
#define JAPANESE_BATTLESHIP_YAMATO_SMOKE_CREATOR_RIGHT_Y_LOCATION 35
//14 INCH
#define JAPANESE_BATTLESHIP_YAMATO_NUMBER_OF_MUZZELES_PER_14_INCH_TURRENT 3
#define JAPANESE_BATTLESHIP_YAMATO_14_INCH_FRONT_GUN_X_LOCATION 295
#define JAPANESE_BATTLESHIP_YAMATO_14_INCH_FRONT_GUN_Y_LOCATION 75
#define JAPANESE_BATTLESHIP_YAMATO_14_INCH_TOP_FRONT_GUN_X_LOCATION 430
#define JAPANESE_BATTLESHIP_YAMATO_14_INCH_TOP_FRONT_GUN_Y_LOCATION 93
//7 INCH
#define JAPANESE_BATTLESHIP_YAMATO_NUMBER_OF_MUZZELES_PER_7_INCH_TURRENT 3
#define JAPANESE_BATTLESHIP_YAMATO_7_INCH_GUN_X_LOCATION 542
#define JAPANESE_BATTLESHIP_YAMATO_7_INCH_GUN_Y_LOCATION 101
//MACHINE GUNS
#define JAPANESE_BATTLESHIP_YAMATO_DUAL_MACHINE_GUN_FRONT_1_X_LOCATION 20
#define JAPANESE_BATTLESHIP_YAMATO_DUAL_MACHINE_GUN_FRONT_1_Y_LOCATION 51
#define JAPANESE_BATTLESHIP_YAMATO_DUAL_MACHINE_GUN_FRONT_2_X_LOCATION 60
#define JAPANESE_BATTLESHIP_YAMATO_DUAL_MACHINE_GUN_FRONT_2_Y_LOCATION 51
#define JAPANESE_BATTLESHIP_YAMATO_DUAL_MACHINE_GUN_FRONT_3_X_LOCATION 170
#define JAPANESE_BATTLESHIP_YAMATO_DUAL_MACHINE_GUN_FRONT_3_Y_LOCATION 51
#define JAPANESE_BATTLESHIP_YAMATO_DUAL_MACHINE_GUN_BACK_1_X_LOCATION 900
#define JAPANESE_BATTLESHIP_YAMATO_DUAL_MACHINE_GUN_BACK_1_Y_LOCATION 70
#define JAPANESE_BATTLESHIP_YAMATO_DUAL_MACHINE_GUN_BACK_2_X_LOCATION 950
#define JAPANESE_BATTLESHIP_YAMATO_DUAL_MACHINE_GUN_BACK_2_Y_LOCATION 48
#define JAPANESE_BATTLESHIP_YAMATO_DUAL_MACHINE_GUN_BACK_3_X_LOCATION 990
#define JAPANESE_BATTLESHIP_YAMATO_DUAL_MACHINE_GUN_BACK_3_Y_LOCATION 44
//75 MM
#define JAPANESE_BATTLESHIP_YAMATO_75MM_GUN_FRONT_X_LOCATION 100
#define JAPANESE_BATTLESHIP_YAMATO_75MM_GUN_FRONT_Y_LOCATION 59
#define JAPANESE_BATTLESHIP_YAMATO_75MM_GUN_BACK_X_LOCATION 830
#define JAPANESE_BATTLESHIP_YAMATO_75MM_GUN_BACK_Y_LOCATION 78
#define JAPANESE_BATTLESHIP_YAMATO_KILL_BASE_SCORE 8000

/*------------------- Japanese Troop Transporter -----------------------*/
#define JAPANESE_TROOP_TRANSPORTER_Z BIG_SHIP_DEFAULT_Z_VALUE
#define JAPANESE_TROOP_TRANSPORTER_NUMBER_OF_ORIGINIAL_HITBOX_POINTS 10
#define JAPANESE_TROOP_TRANSPORTER_NUMBER_OF_PROJECTED_HITBOX_POINTS 10
#define JAPANESE_TROOP_TRANSPORTER_ARMOUR 40
#define JAPANESE_TROOP_TRANSPORTER_WIDTH 512
#define JAPANESE_TROOP_TRANSPORTER_HEIGHT 128
#define JAPANESE_TROOP_TRANSPORTER_KEEL_DEPTH 5
#define JAPANESE_TROOP_TRANSPORTER_LEFT_SMOKE_CREATOR_X_OFFSET -80
#define JAPANESE_TROOP_TRANSPORTER_LEFT_SMOKE_CREATOR_Y_OFFSET 28
#define JAPANESE_TROOP_TRANSPORTER_MIDDLE_SMOKE_CREATOR_X_OFFSET -250
#define JAPANESE_TROOP_TRANSPORTER_MIDDLE_SMOKE_CREATOR_Y_OFFSET 28
#define JAPANESE_TROOP_TRANSPORTER_RIGHT_SMOKE_CREATOR_X_OFFSET -430
#define JAPANESE_TROOP_TRANSPORTER_RIGHT_SMOKE_CREATOR_Y_OFFSET 28
#define JAPANESE_TROOP_TRANSPORTER_DUAL_MACHINE_GUN_FRONT_X_LOCATION 130
#define JAPANESE_TROOP_TRANSPORTER_DUAL_MACHINE_GUN_FRONT_Y_LOCATION 58
#define JAPANESE_TROOP_TRANSPORTER_DUAL_MACHINE_GUN_BACK_X_LOCATION 380
#define JAPANESE_TROOP_TRANSPORTER_DUAL_MACHINE_GUN_BACK_Y_LOCATION 58

/*------------------- Japanese Oil Tanker -----------------------*/
#define JAPANESE_OIL_TANKER_Z BIG_SHIP_DEFAULT_Z_VALUE
#define JAPANESE_OIL_TANKER_NUMBER_OF_ORIGINIAL_HITBOX_POINTS 17
#define JAPANESE_OIL_TANKER_NUMBER_OF_PROJECTED_HITBOX_POINTS 17
#define JAPANESE_OIL_TANKER_ARMOUR 40
#define JAPANESE_OIL_TANKER_WIDTH 512
#define JAPANESE_OIL_TANKER_HEIGHT 128
#define JAPANESE_OIL_TANKER_KEEL_DEPTH 4
#define JAPANESE_OIL_TANKER_LEFT_SMOKE_CREATOR_X_OFFSET -80
#define JAPANESE_OIL_TANKER_LEFT_SMOKE_CREATOR_Y_OFFSET 28
#define JAPANESE_OIL_TANKER_MIDDLE_SMOKE_CREATOR_X_OFFSET -255
#define JAPANESE_OIL_TANKER_MIDDLE_SMOKE_CREATOR_Y_OFFSET 28
#define JAPANESE_OIL_TANKER_RIGHT_SMOKE_CREATOR_X_OFFSET -410
#define JAPANESE_OIL_TANKER_RIGHT_SMOKE_CREATOR_Y_OFFSET 28
#define JAPANESE_OIL_TANKER_DUAL_MACHINE_GUN_FRONT_X_LOCATION 57
#define JAPANESE_OIL_TANKER_DUAL_MACHINE_GUN_FRONT_Y_LOCATION 53
#define JAPANESE_OIL_TANKER_DUAL_MACHINE_GUN_BACK_X_LOCATION 415
#define JAPANESE_OIL_TANKER_DUAL_MACHINE_GUN_BACK_Y_LOCATION 81


//----------------------- BUILDINGS------------------//

/*------------- Default Buildings---------*/
#define LANDING_SURFACE_DEFAULT_ARMOUR 10000
#define LANDING_SURFACE_DEFAULT_HEALTH 1

/*-------------- HQ ----------------*/
//to the left 450 width
// to the right 670 width
#define HQ_Z BUILDINGS_DEFAULT_Z_VALUE
#define HQ_HEALTH 12000
#define HQ_HEALTH_DAMAGED 6010 //when the image of the airport changes to the damaged image
#define HQ_ARMOUR 40
#define HQ_WIDTH 200
#define HQ_HEIGHT 64
#define HQ_HITBOX_WIDTH 200
#define HQ_HITBOX_HEIGHT 56
#define HQ_FLAG_POLE_OFFSET_X -17
#define HQ_KILL_BASE_SCORE 1500

//HQ has a bunch of AAA attached to defend it against planes, spans around 600 to the right and 450 to the left
//right
#define HQ_LIGHT_MACHINE_MACHINE_GUN_RIGHT_1_OFFSET 205
#define HQ_LIGHT_MACHINE_MACHINE_GUN_RIGHT_2_OFFSET 242
#define HQ_TYPE_88_AA_GUN_RIGHT_1_OFFSET 329
#define HQ_TYPE_88_AA_GUN_RIGHT_2_OFFSET 459
#define HQ_CONCRETE_GUN_RIGHT_1_OFFSET 589
//left
#define HQ_LIGHT_MACHINE_MACHINE_GUN_LEFT_1_OFFSET -54
#define HQ_LIGHT_MACHINE_MACHINE_GUN_LEFT_2_OFFSET -91
#define HQ_TYPE_88_AA_GUN_LEFT_1_OFFSET -221
#define HQ_TYPE_88_AA_GUN_LEFT_2_OFFSET -351
#define HQ_CONCRETE_GUN_LEFT_1_OFFSET -451

/*-------------- Com Station ----------------*/
//total width with flag 64, -53 to the left of the com station
#define COMSTATION_Z BUILDINGS_DEFAULT_Z_VALUE
#define COMSTATION_HEALTH 6000
#define COMSTATION_HEALTH_DAMAGED 3510 //when the image of the airport changes to the damaged image
#define COMSTATION_ARMOUR 40
#define COMSTATION_WIDTH 64
#define COMSTATION_HEIGHT 160
#define COMSTATION_HITBOX_WIDTH 64
#define COMSTATION_HITBOX_HEIGHT 152
#define COMSTATION_FLAG_POLE_OFFSET_X -53
#define COMSTATION_FRAMES_UNTIL_NEW_BOMBER_GETS_CALLED  (GFRAMES_PER_SECOND_BACKEND * 60 * 8) //every 8 minutes
#define COMSTATION_BOMBER_SPAWNING_HEIGHT 1600
#define COMSTATION_KILL_BASE_SCORE 300

/*-------------- Airport ----------------*/
//widht to the left 175, witdh to the right 1050
#define AIRPORT_Z BUILDINGS_DEFAULT_Z_VALUE
#define AIRPORT_HEALTH 11000
#define AIRPORT_HEALTH_DAMAGED 5010 //when the image of the airport changes to the damaged image
#define AIRPORT_ARMOUR 40
#define AIRPORT_WIDTH 256
#define AIRPORT_HEIGHT 128
#define AIRPORT_AIRPLANE_POSITION_X_OFFSET 700
#define AIRPORT_LANDING_SURFACE_X_OFFSET -100
#define AIRPORT_LANDING_SURFACE_Y_OFFSET -4 // since Landing surface has height of 4
#define AIRPORT_LANDING_SURFACE_HEIGHT 4
#define AIRPORT_LANDING_SURFACE_WIDTH 1024
#define AIRPORT_LANDING_SURFACE_Z_VALUE LANDING_SURFACE_DEFAULT_Z_VALUE
#define AIRPORT_FLAG_POLE_OFFSET_X -67
#define AIRPORT_TYPE_88_AA_GUN_1_X_POSITION_OFFSET -175
#define AIRPORT_LIGHT_MACHINE_GUN_1_X_POSITION_OFFSET 306
#define AIRPORT_LIGHT_MACHINE_GUN_2_X_POSITION_OFFSET 356
#define AIRPORT_HANGAR_1_OFFSET_X 400
#define AIRPORT_LIGHT_MACHINE_GUN_3_X_POSITION_OFFSET 612
#define AIRPORT_LIGHT_MACHINE_GUN_4_X_POSITION_OFFSET 664
#define AIRPORT_HANGAR_2_OFFSET_X 720
#define AIRPORT_TYPE_88_AA_GUN_2_X_POSITION_OFFSET 950
#define AIRPORT_KILL_BASE_SCORE 750

/*-------------- Hangar ------------------*/
#define HANGAR_Z BUILDINGS_DEFAULT_Z_VALUE
#define HANGAR_HEALTH 4300
#define HANGAR_HEALTH_DAMAGED 2010 //when the image of the airport changes to damaged
#define HANGAR_ARMOUR 40
#define HANGAR_WIDTH 160
#define HANGAR_HEIGHT 128
#define HANGAR_DEFAULT_AIRPLANES 5
#define HANGAR_KILL_BASE_SCORE 125

/*-------------- AA Arterially ------------------*/
#define AAARTERIALLY_DEFAULT_Z_VALUE AA_GUNS_DEFAULT_Z_VALUE

/*-------------- Japanese AA Concrete------------*/
#define JAPANESE_AA_CONCRETE_WIDTH 50
#define JAPANESE_AA_CONCRETE_HEIGHT 48
#define JAPANESE_AA_RELATIVE_CANON_HEIGHT_TO_BASE 43
#define JAPANESE_AA_CONCRETE_CANON_HEIGHT 70
#define JAPANESE_AA_CONCRETE_HEALTH 300
#define JAPANESE_AA_CONCRETE_ARMOR 40
#define JAPANESE_AA_CONCRETE_MAX_RANGE 2500
#define JAPANESE_AA_CONCRETE_MIN_RANGE 100
#define JAPANESE_AA_CONCRETE_MIN_ANGEL 5 // that is between 5 and 175 degrees
#define JAPANESE_AA_CONCRETE_GUN_ROTATION_SPEED 1
#define JAPANESE_AA_CONCRETE_AI_FRAME_WAIT_DELAY_UNTIL_IT_DOES_NEXT_SEARCH_FOR_AIRPLANE 40// aprox every 1.5 secs check if an airplane is in reach
#define JAPANESE_AA_CONCRETE_AI_FRAME_WAIT_DELAY_UNTIL_IT_DOES_NEXT_SEARCH_FOR_AIRPLANE_AFTER_SHOT 150 //every 6.25 secs
#define JAPANESE_AA_CONCRETE_FIRE_SEQUENCE_FRAMES_UNTIL_SWITCH 3
#define JAPANESE_AA_CONCRETE_KILL_BASE_SCORE 80

/*---------------- Japanese AA 75mm Type88 -------------*/
#define JAPANESE_AA_75MM_TYPE88_WIDTH 80
#define JAPANESE_AA_75MM_TYPE88_HEIGHT 32
#define JAPANESE_AA_75MM_TYPE88_HIT_BOX_HEIGHT 16 //make the hitbox a bit smaller otherwise, it is too big and palyer could crash with it
#define JAPANESE_AA_75MM_TYPE88_RELATIVE_CANON_HEIGHT_TO_BASE 20
#define JAPANESE_AA_75MM_TYPE88_BASE_UPPER_S_VALUE 0.625 // only part of the texture is used
#define JAPANESE_AA_75MM_TYPE88_UPPER_T_VALUE 0.9375
#define JAPANESE_AA_75MM_TYPE88_CANON_OFFSET_VALUE_X 6
#define JAPANESE_AA_75MM_TYPE88_CANON_HEIGHT 110 //where the actual weapon is positioned when a projectile is shot
#define JAPANESE_AA_75MM_TYPE88_HEALTH 50
#define JAPANESE_AA_75MM_TYPE88_ARMOR 20
#define JAPANESE_AA_75MM_TYPE88_MAX_RANGE 1200
#define JAPANESE_AA_75MM_TYPE88_MIN_RANGE 50
#define JAPANESE_AA_75MM_TYPE88_MIN_ANGEL 0 // that is between 5 and 175 degrees
#define JAPANESE_AA_75MM_TYPE88_GUN_ROTATION_SPEED 3
#define JAPANESE_AA_75MM_TYPE88_AI_FRAME_WAIT_DELAY_UNTIL_IT_DOES_NEXT_SEARCH_FOR_AIRPLANE 30// aprox every 1 sec, check if an airplane is in reach
#define JAPANESE_AA_75MM_TYPE88_AI_FRAME_WAIT_DELAY_UNTIL_IT_DOES_NEXT_SEARCH_FOR_AIRPLANE_AFTER_SHOT 80// aprox, 2.5 secs between shots
#define JAPANESE_AA_75MM_TYPE88_FIRE_SEQUENCE_FRAMES_UNTIL_SWITCH 2
#define JAPANESE_AA_75MM_TYPE88_ANGLE_RANDOM_OFFSET_LOWER_BOUND -12
#define JAPANESE_AA_75MM_TYPE88_ANGLE_RANDOM_OFFSET_UPPER_BOUND 13
#define JAPANESE_AA_75MM_TYPE88_RANGE_RANDOM_OFFSET_LOWER_BOUND -111
#define JAPANESE_AA_75MM_TYPE88_RANGE_RANDOM_OFFSET_UPPER_BOUND 112
#define JAPANESE_AA_75MM_TYPE88_KILL_BASE_SCORE 55

/*---------------- Japanese AA 20mm Machine Cannon -------------*/
#define JAPANESE_AA_20MM_MACHINE_CANNON_WIDTH 32
#define JAPANESE_AA_20MM_MACHINE_CANNON_HEIGHT 32
#define JAPANESE_AA_20MM_MACHINE_CANNON_RELATIVE_CANON_HEIGHT_TO_BASE 20
#define JAPANESE_AA_20MM_MACHINE_CANNON_BASE_UPPER_S_VALUE 1 // only part of the texture is used
#define JAPANESE_AA_20MM_MACHINE_CANNON_UPPER_T_VALUE 0.5625
#define JAPANESE_AA_20MM_MACHINE_CANNON_OFFSET_VALUE_X 0
#define JAPANESE_AA_20MM_MACHINE_CANNON_GUN_HEIGHT 64
#define JAPANESE_AA_20MM_MACHINE_CANNON_GUN_WIDTH 32
#define JAPANESE_AA_20MM_MACHINE_CANNON_GUN_WEAPON_Y_LOCATION JAPANESE_AA_20MM_MACHINE_CANNON_GUN_HEIGHT // the y location of weapon, relative to the TextureCoordinates Fixpoint
#define JAPANESE_AA_20MM_MACHINE_CANNON_GUN_WEAPON_X_LOCATION 16// the x location of weapon, relative to the TextureCoordinates Fixpoint
#define JAPANESE_AA_20MM_MACHINE_CANNON_HEALTH 50
#define JAPANESE_AA_20MM_MACHINE_CANNON_ARMOR 20
#define JAPANESE_AA_20MM_MACHINE_CANNON_MAX_RANGE 1200
#define JAPANESE_AA_20MM_MACHINE_CANNON_MIN_RANGE 10
#define JAPANESE_AA_20MM_MACHINE_CANNON_MIN_ANGEL 0 // that is between 5 and 175 degrees
#define JAPANESE_AA_20MM_MACHINE_CANNON_ROTATION_SPEED 4
#define JAPANESE_AA_20MM_MACHINE_CANNON_AI_FRAME_WAIT_DELAY_UNTIL_IT_DOES_NEXT_SEARCH_FOR_AIRPLANE 4
#define JAPANESE_AA_20MM_MACHINE_CANNON_AI_FRAME_WAIT_DELAY_UNTIL_IT_DOES_NEXT_SEARCH_FOR_AIRPLANE_AFTER_SHOT 5
#define JAPANESE_AA_20MM_MACHINE_CANNON_FIRE_SEQUENCE_FRAMES_UNTIL_SWITCH 1
#define JAPANESE_AA_20MM_MACHINE_CANNON_KILL_BASE_SCORE 30


//----------------------- GROUND UNITS ------------------//

/*-------------- Basic GROUND UNITS properties -----------------*/

#define BASIC_GROUND_UNIT_DEFAULT_FRAMES_PER_MOVE_HEALTH 1
#define BASIC_GROUND_UNIT_DEFAULT_SQUAD_DISTANCE_BETWEEN_UNITS 10 // how much distance we have between each ground unit in a squad
#define BASIC_GROUND_UNIT_NUMBER_OF_ORIGINIAL_HITBOX_POINTS 5
#define BASIC_GROUND_UNIT_NUMBER_OF_PROJECTED_HITBOX_POINTS 5 //since movement is generally very slow

/*------------ American Sherman Tank -----------------*/
#define AMERICAN_SHERMAN_TANK_Z_COORDINATE TANKS_DEFAULT_Z_VALUE
#define AMERICAN_SHERMAN_TANK_NUMBER_OF_ORIGINIAL_HITBOX_POINTS 10
#define AMERICAN_SHERMAN_TANK_NUMBER_OF_PROJECTED_HITBOX_POINTS 10 //since movement is generally very slow, no need to project the movement
#define AMERICAN_SHERMAN_TANK_WIDTH 128
#define AMERICAN_SHERMAN_TANK_HEIGHT 57
#define AMERICAN_SHERMAN_TANK_HEALTH 300
#define AMERICAN_SHERMAN_TANK_ARMOUR 14
#define AMERICAN_SHERMAN_TANK_GUN_X_LOCATION 10
#define AMERICAN_SHERMAN_TANK_GUN_Y_LOCATION 40
#define AMERICAN_SHERMAN_TANK_FRAMES_NEEDED_FOR_FIRING_ANIMATION (4*4)//frames, each animation frame takes 4 frames
#define AMERICAN_SHERMAN_TANK_MAX_SPEED 3
#define AMERICAN_SHERMAN_TANK_SMOKE_CREATOR_X -52
#define AMERICAN_SHERMAN_TANK_SMOKE_CREATOR_Y 40
#define AMERICAN_SHERMAN_TANK_KILL_BASE_SCORE 50

/*------------ American Anti-Aircraft Sherman Tank -----------------*/
#define AMERICAN_AA_SHERMAN_TANK_Z_COORDINATE TANKS_DEFAULT_Z_VALUE
#define AMERICAN_AA_SHERMAN_TANK_NUMBER_OF_ORIGINIAL_HITBOX_POINTS 8
#define AMERICAN_AA_SHERMAN_TANK_NUMBER_OF_PROJECTED_HITBOX_POINTS 8 //since movement is generally very slow, no need to project the movement
#define AMERICAN_AA_SHERMAN_TANK_WIDTH 128
#define AMERICAN_AA_SHERMAN_TANK_HEIGHT 57
#define AMERICAN_AA_SHERMAN_TANK_HEALTH 300//was 300
#define AMERICAN_AA_SHERMAN_TANK_ARMOUR 14
#define AMERICAN_SHERMAN_TANK_AA_GUN_X_LOCATION -66
#define AMERICAN_SHERMAN_TANK_AA_GUN_Y_LOCATION 45
#define AMERICAN_AA_SHERMAN_TANK_FRAMES_NEEDED_FOR_FIRING_ANIMATION 4 //not really used, but API needs values
#define AMERICAN_AA_SHERMAN_TANK_MAX_WAIT_FRAMES_BEFORE_FIRING 4 //not really used, but API needs values
#define AMERICAN_AA_SHERMAN_TANK_MAX_SPEED 3
#define AMERICAN_AA_SHERMAN_TANK_20MM_MACHINE_CANNON_GUN_WIDTH 48
#define AMERICAN_AA_SHERMAN_TANK_20MM_MACHINE_CANNON_GUN_HEIGHT 16
#define AMERICAN_AA_SHERMAN_TANK_LEFT_MACHINE_GUN_X_POSITION 20
#define AMERICAN_AA_SHERMAN_TANK_LEFT_MACHINE_GUN_Y_POSITION 2
#define AMERICAN_AA_SHERMAN_TANK_RIGHT_MACHINE_GUN_X_POSITION 20
#define AMERICAN_AA_SHERMAN_TANK_RIGHT_MACHINE_GUN_Y_POSITION 8
#define AMERICAN_AA_SHERMAN_TANK_SMOKE_CREATOR_X -52
#define AMERICAN_AA_SHERMAN_TANK_SMOKE_CREATOR_Y 40
#define AMERICAN_AA_SHERMAN_TANK_DUST_CREATOR_X 5
#define AMERICAN_AA_SHERMAN_TANK_DUST_CREATOR_Y -25
#define AMERICAN_AA_SHERMAN_TANK_KILL_BASE_SCORE 35

/*-------------American Rifleman---------*/
#define AMERICAN_RIFLEMAN_Z_COORDINATE SOLDIERS_DEFAULT_Z_VALUE
#define AMERICAN_RIFLEMAN_WIDTH 32
#define AMERICAN_RIFLEMAN_HEIGHT 32
#define AMERICAN_RIFLEMAN_HEALTH 6
#define AMERICAN_RIFLEMAN_ARMOUR 0
#define AMERICAN_RIFLEMAN_8MM_RIFLE_X_LOCATION 3
#define AMERICAN_RIFLEMAN_8MM_RIFLE_Y_LOCATION 20
#define AMERICAN_RIFLEMAN_FRAMES_NEEDED_FOR_FIRING_ANIMATION (2 * 4)//frames, each animation frame takes 2 frames
#define AMERICAN_RIFLEMAN_MAX_SPEED 2
#define AMERICAN_RIFLEMAN_KILL_BASE_SCORE 10

/*-------------American Rocketman---------*/
#define AMERICAN_ROCKETMAN_Z_COORDINATE SOLDIERS_DEFAULT_Z_VALUE
#define AMERICAN_ROCKETMAN_WIDTH 32
#define AMERICAN_ROCKETMAN_HEIGHT 32
#define AMERICAN_ROCKETMAN_HEALTH 6
#define AMERICAN_ROCKETMAN_ARMOUR 0
#define AMERICAN_ROCKETMAN_GRENADE_LAUNCHER_X_LOCATION 3
#define AMERICAN_ROCKETMAN_GRENADE_LAUNCHER_Y_LOCATION 20
#define AMERICAN_ROCKETMAN_FRAMES_UNTIL_SWITCH_SHOOTING_ANIMATION 4
#define AMERICAN_ROCKETMAN_FRAMES_NEEDED_FOR_FIRING_ANIMATION (AMERICAN_ROCKETMAN_FRAMES_UNTIL_SWITCH_SHOOTING_ANIMATION*4)//frames, each animation frame takes 2 frames
#define AMERICAN_ROCKETMAN_MAX_SPEED 2
#define AMERICAN_ROCKETMAN_KILL_BASE_SCORE 20

/*------------ Japanese 96 Chi Ha Tank -----------------*/
#define JAPANESE_97_CHI_HA_TANK_Z_COORDINATE TANKS_DEFAULT_Z_VALUE
#define JAPANESE_97_CHI_HA_TANK_NUMBER_OF_ORIGINIAL_HITBOX_POINTS 9
#define JAPANESE_97_CHI_HA_TANK_NUMBER_OF_PROJECTED_HITBOX_POINTS 9 //since movement is generally very slow, no need to project the movement
#define JAPANESE_97_CHI_HA_TANK_WIDTH 128
#define JAPANESE_97_CHI_HA_TANK_HEIGHT 57
#define JAPANESE_97_CHI_HA_TANK_HEALTH 300
#define JAPANESE_97_CHI_HA_TANK_ARMOUR 14
#define JAPANESE_97_CHI_HA_TANK_GUN_X_LOCATION 10
#define JAPANESE_97_CHI_HA_TANK_GUN_Y_LOCATION 40
#define JAPANESE_97_CHI_HA_TANK_FRAMES_NEEDED_FOR_FIRING_ANIMATION (4*4)//frames, each animation frame takes 4 frames
#define JAPANESE_97_CHI_HA_TANK_MAX_SPEED 3
#define JAPANESE_97_CHI_HA_TANK_SMOKE_CREATOR_X -40
#define JAPANESE_97_CHI_HA_TANK_SMOKE_CREATOR_Y 40
#define JAPANESE_97_CHI_HA_TANK_KILL_BASE_SCORE 50

/*------------ Japanese Anti-Aircraft 96 Chi Ha Tank -----------------*/
#define JAPANESE_AA_97_CHI_HA_TANK_Z_COORDINATE TANKS_DEFAULT_Z_VALUE
#define JAPANESE_AA_97_CHI_HA_TANK_NUMBER_OF_ORIGINIAL_HITBOX_POINTS 9
#define JAPANESE_AA_97_CHI_HA_TANK_NUMBER_OF_PROJECTED_HITBOX_POINTS 9 //since movement is generally very slow, no need to project the movement
#define JAPANESE_AA_97_CHI_HA_TANK_WIDTH 128
#define JAPANESE_AA_97_CHI_HA_TANK_HEIGHT 57
#define JAPANESE_AA_97_CHI_HA_TANK_HEALTH 300//was 300
#define JAPANESE_AA_97_CHI_HA_TANK_ARMOUR 14
#define JAPANESE_AA_97_CHI_HA_TANK_GUN_X_LOCATION -52
#define JAPANESE_AA_97_CHI_HA_TANK_GUN_Y_LOCATION 38
#define JAPANESE_AA_97_CHI_HA_TANK_FRAMES_NEEDED_FOR_FIRING_ANIMATION 4 //not really used, but API needs values
#define JAPANESE_AA_97_CHI_HA_TANK_MAX_WAIT_FRAMES_BEFORE_FIRING 4 //not really used, but API needs values
#define JAPANESE_AA_97_CHI_HA_TANK_MAX_SPEED 3
#define JAPANESE_AA_97_CHI_HA_TANK_20MM_MACHINE_CANNON_GUN_WIDTH 16
#define JAPANESE_AA_97_CHI_HA_TANK_20MM_MACHINE_CANNON_GUN_HEIGHT 48
#define JAPANESE_AA_97_CHI_HA_TANK_SMOKE_CREATOR_X -40
#define JAPANESE_AA_97_CHI_HA_TANK_SMOKE_CREATOR_Y 40
#define JAPANESE_AA_97_CHI_HA_TANK_KILL_BASE_SCORE 35

/*-------------Japanese Rifleman---------*/
#define JAPANESE_RIFLEMAN_Z_COORDINATE SOLDIERS_DEFAULT_Z_VALUE
#define JAPANESE_RIFLEMAN_WIDTH 32
#define JAPANESE_RIFLEMAN_HEIGHT 32
#define JAPANESE_RIFLEMAN_HEALTH 6
#define JAPANESE_RIFLEMAN_ARMOUR 0
#define JAPANESE_RIFLEMAN_8MM_RIFLE_X_LOCATION 3
#define JAPANESE_RIFLEMAN_8MM_RIFLE_Y_LOCATION 20
#define JAPANESE_RIFLEMAN_FRAMES_NEEDED_FOR_FIRING_ANIMATION (2*4)//frames, each animation frame takes 2 frames
#define JAPANESE_RIFLEMAN_MAX_SPEED 2
#define JAPANESE_RIFLEMAN_KILL_BASE_SCORE 10

/*-------------Japanese Rocketman---------*/
#define JAPANESE_ROCKETMAN_Z_COORDINATE SOLDIERS_DEFAULT_Z_VALUE
#define JAPANESE_ROCKETMAN_WIDTH 32
#define JAPANESE_ROCKETMAN_HEIGHT 32
#define JAPANESE_ROCKETMAN_HEALTH 6
#define JAPANESE_ROCKETMAN_ARMOUR 0
#define JAPANESE_ROCKETMAN_GRENADE_LAUNCHER_X_LOCATION 3
#define JAPANESE_ROCKETMAN_GRENADE_LAUNCHER_Y_LOCATION 20
#define JAPANESE_ROCKETMAN_FRAMES_UNTIL_SWITCH_SHOOTING_ANIMATION 4
#define JAPANESE_ROCKETMAN_FRAMES_NEEDED_FOR_FIRING_ANIMATION (JAPANESE_ROCKETMAN_FRAMES_UNTIL_SWITCH_SHOOTING_ANIMATION*4)//frames, each animation frame takes 2 frames
#define JAPANESE_ROCKETMAN_MAX_SPEED 2
#define JAPANESE_ROCKETMAN_KILL_BASE_SCORE 20

//-------------------Projectiles-------------//

/*-------------Basic Porjectile---------*/
#define BASIC_PROJECTILE_DEFAULT_Z_COORDINATE PROJECTILE_DEFAULT_Z_VALUE
#define BASIC_PROJECTILE_HEALTH 1
#define BASIC_PROJECTILE_DEFAULT_FRAMES_PER_MOVE 1
#define BASIC_PROJECTILE_DEFAULT_ARMOR 0
#define GRAVITATIONAL_FACTOR_FRAMES_UNTIL_SPEED_UPDATE 5
#define GRAVITATIONAL_FACTOR_SPEED_INCREASE_VALUE 1

/*-------------88mm Explosive Shell-------------------*/
#define EXPLOSIVE88MMSHELL_SPEED 20
#define EXPLOSIVE88MMSHELL_WIDTH 16
#define EXPLOSIVE88MMSHELL_HEIGHT 4

/*-------------75mm Explosive Shell-------------------*/
#define EXPLOSIVE75MMSHELL_SPEED 22
#define EXPLOSIVE75MMSHELL_WIDTH 8
#define EXPLOSIVE75MMSHELL_HEIGHT 2

//*------------Explosive 7 Inch Shell -------------//
#define EXPLOSIVE_7_INCH_SHELL_RANGE 50000 //make sure it only gets destroyed if it hits target or hits ground
#define EXPLOSIVE_7_INCH_SHELL_WIDTH 16
#define EXPLOSIVE_7_INCH_SHELL_HEIGHT 4

//*------------Explosive 14 Inch Shell -------------//
#define EXPLOSIVE_14_INCH_SHELL_RANGE 50000 //make sure it only gets destroyed if it hits target or hits ground
#define EXPLOSIVE_14_INCH_SHELL_WIDTH 32
#define EXPLOSIVE_14_INCH_SHELL_HEIGHT 8

//*------------80 mm Tank Shell -------------//
#define TANKSHELL80MM_SPEED 25
#define TANKSHELL80MM_RANGE 3000 //make sure it only gets destroyed if it hits target or hits ground
#define TANKSHELL80MM_WIDTH 16
#define TANKSHELL80MM_HEIGHT 4
#define TANKSHELL80MM_DAMAGE 100
#define TANKSHELL80MM_AMORPENETRATION 25

//*------------Propelled Grenade-------------//
#define PROPELLEDGRENADE_SPEED 25
#define PROPELLEDGRENADE_RANGE 3000 //make sure it only gets destroyed if it hits target or hits ground
#define PROPELLEDGRENADE_WIDTH 4
#define PROPELLEDGRENADE_HEIGHT 2
#define PROPELLEDGRENADE_SPEED_INCREASE_VALUE (1)

/*------------- Standard Rocket -------------------*/
#define STANDARD_ROCKET_SPEED 25
#define STANDARD_ROCKET_WIDTH 64
#define STANDARD_ROCKET_SMOKE_AND_FIRE_WITDH 32
#define STANDARD_ROCKET_HEIGHT 16
#define STANDARD_ROCKET_RANGE 1500
#define STANDARD_ROCKET_ARMORPENETRATION 25
#define STANDARD_ROCKET_DAMAGAE 1000

//*------------Cannon 20mm Bullet-------------//
#define BULLETCANNON20MM_SPEED 20
#define BULLETCANNON20MM_RANGE 1000
#define BULLETCANNON20MM_WIDTH 24
#define BULLETCANNON20MM_HEIGHT 6
#define BULLETCANNON20MM_AMORPENETRATION 6
#define BULLETCANNON20MM_DAMAGE 20
#define BULLETCANNON20MM_FRAMES_FOR_SMOKE_TRIAL 2

//*------------13mm Bullet-------------//
#define BULLET13MM_SPEED 25
#define BULLET13MM_RANGE 1400
#define BULLET13MM_WIDTH 16
#define BULLET13MM_HEIGHT 4
#define BULLET13MM_AMORPENETRATION 6
#define BULLET13MM_DAMAGE 6

//*------------8mm Bullet-------------//
#define BULLET8MM_SPEED 25
#define BULLET8MM_RANGE 1400
#define BULLET8MM_WIDTH 8
#define BULLET8MM_HEIGHT 2
#define BULLET8MM_AMORPENETRATION 6
#define BULLET8MM_DAMAGE 4

//*------------Rifle Bullet-------------//
#define BULLET_RIFLE_SPEED 25
#define BULLET_RIFLE_WIDTH 8
#define BULLET_RIFLE_HEIGHT 2
#define BULLET_RIFLE_AMORPENETRATION 1
#define BULLET_RIFLE_DAMAGE 3
#define BULLET_RIFLE_SPEED_INCREASE_VALUE 1

//*------------Under Water Torpedo-------------//
#define UNDER_WATER_TORPEDO_SPEED 11
#define UNDER_WATER_TORPEDO_RANGE 500
#define UNDER_WATER_TORPEDO_WIDTH 25
#define UNDER_WATER_TORPEDO_HEIGHT 8
#define UNDER_WATER_TORPEDO_ARMORPENETRATION 100
#define UNDER_WATER_TORPEDO_DAMAGE 3500
#define UNDER_WATER_TORPED_GAS_RELEASE_SEQUENCE_FRAMES_UNTIL_SWITCH 4
#define UNDER_WATER_TORPED_MAX_SPEED_OTHERWISE_EXPLODE 100
#define UNDER_WATER_TORPED_MAX_DROP_HEIGHT_OTHERWISE_EXPLODE (60)

/*------------- Bombs ----------------*/
#define BASIC_PROJECTILE_NUMBER_OF_ORIGINIAL_HITBOX_POINTS 5
#define BASIC_PROJECTILE_NUMBER_OF_PROJECTED_HITBOX_POINTS 7
#define BOMB_1000KG_WIDTH 52
#define BOMB_1000KG_HEIGHT 16
#define BOMB_500KG_WIDTH 30
#define BOMB_500KG_HEIGHT 8
#define BOMB_100KG_WIDTH 19
#define BOMB_100KG_HEIGHT 6
#define CLUSTER_BOMB_WIDTH 40
#define CLUSTER_BOMB_HEIGHT 20
#define CLUSTER_BOMB_MINI_BOMBS_PER_BOMB 30 //15
#define TORPEDO_WIDTH 58
#define TORPEDO_HEIGHT 8
#define BOMB_DEFAULT_RANGE 100000 // something big since bombs don't really vanish

//-----------------EXPLOSIONS-----------------------//

/*----------- Basic Explosion ------------*/
#define EXPLOSION_DEFAULT_HEALTH 1000
#define EXPLOSION_DEFAULT_ARMOR 1000
#define EXPLOSOPN_NO_EXPLOSION_WIDTH 0 //used to signal that if used by projectile that it has no explosion

/*--------- 1000kg Explosion in Air ------------*/
#define EXPLOSION_IN_AIR_1000KG_ARMOR_PENETRATION 50
#define EXPLOSION_IN_AIR_1000KG_DAMAGE 1000
#define EXPLOSION_IN_AIR_1000KG_WIDTH 100
#define EXPLOSION_IN_AIR_1000KG_HEIGHT 100
#define EXPLOSION_IN_AIR_1000KG_TOTAL_TIME_FOR_EXPLOSION 20
#define EXPLOSION_IN_AIR_1000KG_FRAME_OFFSET_FOR_COLLISION_CHECK (EXPLOSION_IN_AIR_1000KG_TOTAL_TIME_FOR_EXPLOSION/5)

/*--------- 1000kg Explosion-----------*/
#define EXPLOSION_1000KG_ARMOR_PENETRATION 100
#define EXPLOSION_1000KG_DAMAGE 1000
#define EXPLOSION_1000KG_WIDTH 100
#define EXPLOSION_1000KG_HEIGHT 100
#define EXPLOSION_1000KG_TOTAL_TIME_FOR_EXPLOSION 20
#define EXPLOSION_1000KG_FRAME_OFFSET_FOR_COLLISION_CHECK (EXPLOSION_1000KG_TOTAL_TIME_FOR_EXPLOSION/5)

/*--------- 14 Inch Shell Explosion-----------*/
#define EXPLOSION_14INCH_SHELL_ARMOR_PENETRATION 100
#define EXPLOSION_14INCH_SHELL_DAMAGE 4000
#define EXPLOSION_14INCH_SHELL_WIDTH 200
#define EXPLOSION_14INCH_SHELL_HEIGHT 200
#define EXPLOSION_14INCH_SHELL_TOTAL_TIME_FOR_EXPLOSION 20
#define EXPLOSION_14INCH_SHELL_FRAME_OFFSET_FOR_COLLISION_CHECK (EXPLOSION_1000KG_TOTAL_TIME_FOR_EXPLOSION/5)

/*-------- 500kg Explosion------------*/
#define EXPLOSION_500KG_ARMOR_PENETRATION 50
#define EXPLOSION_500KG_DAMAGE 400
#define EXPLOSION_500KG_WIDTH 50
#define EXPLOSION_500KG_HEIGHT 50
#define EXPLOSION_500KG_TOTAL_TIME_FOR_EXPLOSION 20

/*-------- 500kg Explosion in Air------------*/
#define EXPLOSION_IN_AIR_500KG_ARMOR_PENETRATION 15
#define EXPLOSION_IN_AIR_500KG_DAMAGE 40
#define EXPLOSION_IN_AIR_500KG_WIDTH 50
#define EXPLOSION_IN_AIR_500KG_HEIGHT 50
#define EXPLOSION_IN_AIR_500KG_TOTAL_TIME_FOR_EXPLOSION 20
#define EXPLOSION_IN_AIR_500KG_FRAME_OFFSET_FOR_COLLISION_CHECK (EXPLOSION_IN_AIR_500KG_TOTAL_TIME_FOR_EXPLOSION/5)

/*-------- 100kg Explosion------------*/
#define EXPLOSION_100KG_ARMOR_PENETRATION 25
#define EXPLOSION_100KG_DAMAGE 100
#define EXPLOSION_100KG_WIDTH 25
#define EXPLOSION_100KG_HEIGHT 25
#define EXPLOSION_100KG_TOTAL_TIME_FOR_EXPLOSION 20

/*--------- 100kg Explosion in Air ------------*/
#define EXPLOSION_IN_AIR_100KG_ARMOR_PENETRATION 15
#define EXPLOSION_IN_AIR_100KG_DAMAGE 38
#define EXPLOSION_IN_AIR_100KG_WIDTH 25
#define EXPLOSION_IN_AIR_100KG_HEIGHT 25
#define EXPLOSION_IN_AIR_100KG_TOTAL_TIME_FOR_EXPLOSION 20
#define EXPLOSION_IN_AIR_100KG_FRAME_OFFSET_FOR_COLLISION_CHECK (EXPLOSION_IN_AIR_100KG_TOTAL_TIME_FOR_EXPLOSION/5)

/*-------- 1000kg Explosion in Water-----------*/
#define EXPLOSION_1000KG_IN_WATER_ARMOR_PENETRATION 30
#define EXPLOSION_1000KG_IN_WATER_DAMAGE 200
#define EXPLOSION_1000KG_IN_WATER_WIDTH 75
#define EXPLOSION_1000KG_IN_WATER_HEIGHT 75
#define EXPLOSION_1000KG_IN_WATER_TOTAL_TIME_FOR_EXPLOSION 20

/*-------- 14 Inch Shell Explosion in Water-----------*/
#define EXPLOSION_14INCH_SHELL_IN_WATER_ARMOR_PENETRATION 30
#define EXPLOSION_14INCH_SHELL_IN_WATER_DAMAGE 400
#define EXPLOSION_14INCH_SHELL_IN_WATER_WIDTH 102
#define EXPLOSION_14INCH_SHELL_IN_WATER_HEIGHT 102
#define EXPLOSION_14INCH_SHELL_IN_WATER_TOTAL_TIME_FOR_EXPLOSION 20

/*-------- 500kg Explosion in Water------------*/
#define EXPLOSION_500KG_IN_WATER_ARMOR_PENETRATION 10
#define EXPLOSION_500KG_IN_WATER_DAMAGE 70
#define EXPLOSION_500KG_IN_WATER_WIDTH 50
#define EXPLOSION_500KG_IN_WATER_HEIGHT 50
#define EXPLOSION_500KG_IN_WATER_TOTAL_TIME_FOR_EXPLOSION 20

/*-------- 100kg Explosion in Water------------*/
#define EXPLOSION_100KG_IN_WATER_ARMOR_PENETRATION 2
#define EXPLOSION_100KG_IN_WATER_DAMAGE 15
#define EXPLOSION_100KG_IN_WATER_WIDTH 25
#define EXPLOSION_100KG_IN_WATER_HEIGHT 25
#define EXPLOSION_100KG_IN_WATER_TOTAL_TIME_FOR_EXPLOSION 20

/*-------- Water Splash ------------*/
#define WATER_SPLASH_ARMOR_PENETRATION 0
#define WATER_SPLASH_DAMAGE 2
#define WATER_SPLASH_WIDTH 8
#define WATER_SPLASH_HEIGHT 8
#define WATER_SPLASH_TOTAL_TIME_FOR_EXPLOSION 10

//-------------------Weapons-------------------//

/*-------------8mm Rifle---------*/
#define RIFLE_DEFAULT_AMMUNITION 1
#define RIFLE_DEFAULT_LIMITED_AMMUNITION FALSE
#define RIFLE_UPPER_ANGLE_RANDOM_VALUE 12
#define RIFLE_LOWER_ANGLE_RANDOM_VALUE -2
#define RIFLE_EXTRA_BULLET_SPEED_LOWER_VALUE -5
#define RIFLE_EXTRA_BULLET_SPEED_UPPER_VALUE 5
#define RIFLE_FRAMES_BETWEEN_FIRE (GFRAMES_PER_SECOND_BACKEND * 5) //5 secs

/*-------------Grenade Launcher---------*/
#define GRENADELAUNCHER_DEFAULT_AMMUNITION 1
#define GRENADELAUNCHER_DEFAULT_LIMITED_AMMUNITION FALSE
#define GRENADELAUNCHER_UPPER_ANGLE_RANDOM_VALUE 14
#define GRENADELAUNCHER_LOWER_ANGLE_RANDOM_VALUE 2
#define GRENADELAUNCHER_FRAMES_BETWEEN_FIRE (GFRAMES_PER_SECOND_BACKEND * 10) //10 sec
#define GRENADELAUNCHER_EXTRA_BULLET_SPEED_LOWER_VALUE -2
#define GRENADELAUNCHER_EXTRA_BULLET_SPEED_UPPER_VALUE 12

/*------------- Tank Gun 88 mm---------*/
#define TANKGUN88MM_DEFAULT_AMMUNITION 1
#define TANKGUN88MM_DEFAULT_LIMITED_AMMUNITION FALSE
#define TANKGUN88MM_UPPER_ANGLE_RANDOM_VALUE 10
#define TANKGUN88MM_LOWER_ANGLE_RANDOM_VALUE -4
#define TANKGUN88MM_EXTRA_BULLET_SPEED_LOWER_VALUE -4
#define TANKGUN88MM_EXTRA_BULLET_SPEED_UPPER_VALUE 12
#define TANKGUN88MM_FRAMES_BETWEEN_FIRE (GFRAMES_PER_SECOND_BACKEND * 20) //20 sec

/*-------------20mm Cannon---------*/
#define CANNON_20MM_DEFAULT_AMMUNITION 1
#define CANNON_20MM_DEFAULT_LIMITED_AMMUNITION FALSE
#define CANNON_20MM_FRAMES_BETWEEN_FIRE 15

/*-------------13mm Machine Gun---------*/
#define MACHINEGUN_13MM_DEFAULT_AMMUNITION 1
#define MACHINEGUN_13MM_DEFAULT_LIMITED_AMMUNITION FALSE
#define MACHINEGUN_13MM_FRAMES_BETWEEN_FIRE 6

/*-------------8mm Machine Gun---------*/
#define MACHINEGUN_8MM_DEFAULT_AMMUNITION 1
#define MACHINEGUN_8MM_DEFAULT_LIMITED_AMMUNITION FALSE
#define MACHINEGUN_8MM_FRAMES_BETWEEN_FIRE 5

/*----------AA 88mm Gun--------*/
#define GUNAA88MM_DEFAULT_AMMUNITION 1
#define GUNAA88MM_DEFAULT_LIMITED_AMMUNITION FALSE
#define GUNAA88MM_FRAMES_BETWEEN_FIRE (GFRAMES_PER_SECOND_BACKEND * 4) //4 secs

/*----------AA 75mm Gun--------*/
#define GUNAA75MM_DEFAULT_AMMUNITION 1
#define GUNAA75MM_DEFAULT_LIMITED_AMMUNITION FALSE
#define GUNAA75MM_FRAMES_BETWEEN_FIRE 10

/*------------ Bomb Weapons----------*/
#define WEAPON_BOMB_1000KG_FRAMES_BETWEEN_FIRE 30
#define WEAPON_BOMB_500KG_FRAMES_BETWEEN_FIRE 20
#define WEAPON_BOMB_100KG_FRAMES_BETWEEN_FIRE 5
#define WEAPON_BOMB_100KG_EXTRA_WEAPON_X_OFFSET -20
#define WEAPON_CLUSTER_BOMB_FRAMES_BETWEEN_FIRE 30
#define WEAPON_STANDARD_ROCKET_FRAMES_BETWEEN_FIRE 10
#define WEAPON_TORPEDO_FRAMES_BETWEEN_FIRE 30

/*------------ Aircraft Weapon Cannon 20 mm-----------------------*/
#define WEAPON_AIRCRAFT_CANNON_20MM_FRAMES_BETWEEN_FIRE CANNON_20MM_FRAMES_BETWEEN_FIRE
#define WEAPON_AIRCRAFT_CANNON_20MM_ANIMATION_LENGTH_IN_FRAMES 3
#define WEAPON_AIRCRAFT_CANNON_20MM_WIDTH 14
#define WEAPON_AIRCRAFT_CANNON_20MM_HEIGHT 6

/*------------ Aircraft Weapon Machine Gun 13 mm-----------------------*/
#define WEAPON_AIRCRAFT_MACHINE_GUN_13MM_FRAMES_BETWEEN_FIRE MACHINEGUN_13MM_FRAMES_BETWEEN_FIRE
#define WEAPON_AIRCRAFT_MACHINE_GUN_13MM_ANIMATION_LENGTH_IN_FRAMES 3
#define WEAPON_AIRCRAFT_MACHINE_GUN_13MM_WIDTH 10
#define WEAPON_AIRCRAFT_MACHINE_GUN_13MM_HEIGHT 6

/*------------ Aircraft Weapon Machine Gun 8 mm-----------------------*/
#define WEAPON_AIRCRAFT_MACHINE_GUN_8MM_FRAMES_BETWEEN_FIRE MACHINEGUN_8MM_FRAMES_BETWEEN_FIRE
#define WEAPON_AIRCRAFT_MACHINE_GUN_8MM_ANIMATION_LENGTH_IN_FRAMES 3
#define WEAPON_AIRCRAFT_MACHINE_GUN_8MM_WIDTH 7
#define WEAPON_AIRCRAFT_MACHINE_GUN_8MM_HEIGHT 4

/*------------ STANDARD ROCKET WEAPON-----------------*/
#define WEAPON_STANDARD_ROCKET_WIDTH 32
#define WEAPON_STANDARD_ROCKET_HEIGHT 16

/*----------BACK GUN MachineGun 8mm----------------*/
#define WEAPON_BACK_GUN_MACHINE_GUN_8MM_FRAMES_BETWEEN_FIRE 4
#define WEAPON_BACK_GUN_MACHINE_GUN_8MM_FIRE_SEQUENCE_FRAMES_UNTIL_SWITCH 1
#define WEAPON_BACK_GUN_MACHINE_GUN_8MM_WIDTH 23
#define WEAPON_BACK_GUN_MACHINE_GUN_8MM_HEIGHT 4
#define WEAPON_BACK_GUN_MACHINE_GUN_8MM_MACHINE_GUN_X_POSITION 14
#define WEAPON_BACK_GUN_MACHINE_GUN_8MM_MACHINE_GUN_Y_POSITION 0
#define WEAPON_BACK_GUN_MACHINE_GUN_8MM_ROTATION_SPEED 4
#define WEAPON_BACK_GUN_MACHINE_GUN_8MM_MIN_RANGE 10
#define WEAPON_BACK_GUN_MACHINE_GUN_8MM_MAX_RANGE BULLET8MM_RANGE
#define WEAPON_BACK_GUN_MACHINE_GUN_8MM_WAIT_FRAMES_BETWEEN_FIRE MACHINEGUN_8MM_FRAMES_BETWEEN_FIRE
#define WEAPON_BACK_GUN_MACHINE_GUN_8MM_AI_WAIT_FRAMES_AFTER_SEARCH 4
#define WEAPON_BACK_GUN_MACHINE_GUN_8MM_AI_FIRES_PER_BURST 4
#define WEAPON_BACK_GUN_MACHINE_GUN_8MM_AI_WAIT_FRAMES_AFTER_SHOOT (WEAPON_BACK_GUN_MACHINE_GUN_8MM_WAIT_FRAMES_BETWEEN_FIRE * 2)

/*----------BACK GUN Double MachineGun 8mm----------------*/
#define WEAPON_BACK_GUN_DOUBLE_MACHINE_GUN_8MM_FRAMES_BETWEEN_FIRE 4
#define WEAPON_BACK_GUN_DOUBLE_MACHINE_GUN_8MM_FIRE_SEQUENCE_FRAMES_UNTIL_SWITCH 1
#define WEAPON_BACK_GUN_DOUBLE_MACHINE_GUN_8MM_WIDTH 24
#define WEAPON_BACK_GUN_DOUBLE_MACHINE_GUN_8MM_HEIGHT 8
#define WEAPON_BACK_GUN_DOUBLE_MACHINE_GUN_8MM_MACHINE_GUN_1_X_POSITION 14
#define WEAPON_BACK_GUN_DOUBLE_MACHINE_GUN_8MM_MACHINE_GUN_1_Y_POSITION 0
#define WEAPON_BACK_GUN_DOUBLE_MACHINE_GUN_8MM_MACHINE_GUN_2_X_POSITION 14
#define WEAPON_BACK_GUN_DOUBLE_MACHINE_GUN_8MM_MACHINE_GUN_2_Y_POSITION 4
#define WEAPON_BACK_GUN_DOUBLE_MACHINE_GUN_8MM_ROTATION_SPEED 2
#define WEAPON_BACK_GUN_DOUBLE_MACHINE_GUN_8MM_MIN_RANGE 10
#define WEAPON_BACK_GUN_DOUBLE_MACHINE_GUN_8MM_MAX_RANGE BULLET8MM_RANGE
#define WEAPON_BACK_GUN_DOUBLE_MACHINE_GUN_8MM_WAIT_FRAMES_BETWEEN_FIRE MACHINEGUN_8MM_FRAMES_BETWEEN_FIRE
#define WEAPON_BACK_GUN_DOUBLE_MACHINE_GUN_8MM_AI_WAIT_FRAMES_AFTER_SEARCH 4
#define WEAPON_BACK_GUN_DOUBLE_MACHINE_GUN_8MM_AI_FIRES_PER_BURST 4
#define WEAPON_BACK_GUN_DOUBLE_MACHINE_GUN_8MM_AI_WAIT_FRAMES_AFTER_SHOOT (WEAPON_BACK_GUN_DOUBLE_MACHINE_GUN_8MM_WAIT_FRAMES_BETWEEN_FIRE * 2)


/*----------BACK GUN Double MachineGun 13mm----------------*/
#define WEAPON_BACK_GUN_DOUBLE_MACHINE_GUN_13MM_FRAMES_BETWEEN_FIRE 4
#define WEAPON_BACK_GUN_DOUBLE_MACHINE_GUN_13MM_FIRE_SEQUENCE_FRAMES_UNTIL_SWITCH 1
#define WEAPON_BACK_GUN_DOUBLE_MACHINE_GUN_13MM_WIDTH 24
#define WEAPON_BACK_GUN_DOUBLE_MACHINE_GUN_13MM_HEIGHT 4
#define WEAPON_BACK_GUN_DOUBLE_MACHINE_GUN_13MM_MACHINE_GUN_1_X_POSITION 14
#define WEAPON_BACK_GUN_DOUBLE_MACHINE_GUN_13MM_MACHINE_GUN_1_Y_POSITION 0
#define WEAPON_BACK_GUN_DOUBLE_MACHINE_GUN_13MM_MACHINE_GUN_2_X_POSITION 14
#define WEAPON_BACK_GUN_DOUBLE_MACHINE_GUN_13MM_MACHINE_GUN_2_Y_POSITION 4
#define WEAPON_BACK_GUN_DOUBLE_MACHINE_GUN_13MM_ROTATION_SPEED 2
#define WEAPON_BACK_GUN_DOUBLE_MACHINE_GUN_13MM_MIN_RANGE 10
#define WEAPON_BACK_GUN_DOUBLE_MACHINE_GUN_13MM_MAX_RANGE BULLET13MM_RANGE
#define WEAPON_BACK_GUN_DOUBLE_MACHINE_GUN_13MM_WAIT_FRAMES_BETWEEN_FIRE MACHINEGUN_13MM_FRAMES_BETWEEN_FIRE
#define WEAPON_BACK_GUN_DOUBLE_MACHINE_GUN_13MM_AI_WAIT_FRAMES_AFTER_SEARCH 4
#define WEAPON_BACK_GUN_DOUBLE_MACHINE_GUN_13MM_AI_FIRES_PER_BURST 4
#define WEAPON_BACK_GUN_DOUBLE_MACHINE_GUN_13MM_AI_WAIT_FRAMES_AFTER_SHOOT (WEAPON_BACK_GUN_DOUBLE_MACHINE_GUN_13MM_WAIT_FRAMES_BETWEEN_FIRE * 2)


// ---------------------- SHIP GUNS ---------------------- //

/*------------ Dual Anti-Aircraft Machine Gun -----------------*/
#define DUAL_MACHINE_GUN_Z_COORDINATE NOT_IMPORTANT_Z_VALUE
#define DUAL_MACHINE_GUN_NUMBER_OF_ORIGINIAL_HITBOX_POINTS 8
#define DUAL_MACHINE_GUN_NUMBER_OF_PROJECTED_HITBOX_POINTS 8 //since movement is generally very slow, no need to project the movement
#define DUAL_MACHINE_GUN_WIDTH 32
#define DUAL_MACHINE_GUN_HEIGHT 32
#define DUAL_MACHINE_GUN_20MM_MACHINE_CANNON_GUN_WIDTH 34
#define DUAL_MACHINE_GUN_20MM_MACHINE_CANNON_GUN_HEIGHT 8
#define DUAL_MACHINE_GUN_CENTER_X_POSITION -16
#define DUAL_MACHINE_GUN_CENTER_Y_POSITION 23
#define DUAL_MACHINE_GUN_LEFT_MACHINE_GUN_X_POSITION 64
#define DUAL_MACHINE_GUN_LEFT_MACHINE_GUN_Y_POSITION 2
#define DUAL_MACHINE_GUN_RIGHT_MACHINE_GUN_X_POSITION 64
#define DUAL_MACHINE_GUN_RIGHT_MACHINE_GUN_Y_POSITION 5
#define DUAL_MACHINE_GUN_FRAMES_BETWEEN_FIRE (MACHINEGUN_13MM_FRAMES_BETWEEN_FIRE)

/*------------ Dual 75mm Gun -----------------*/
#define DUAL_75MM_GUN_Z_COORDINATE NOT_IMPORTANT_Z_VALUE
#define DUAL_75MM_GUN_NUMBER_OF_ORIGINIAL_HITBOX_POINTS 8
#define DUAL_75MM_GUN_NUMBER_OF_PROJECTED_HITBOX_POINTS 8 //since movement is generally very slow, no need to project the movement
#define DUAL_75MM_GUN_WIDTH 64
#define DUAL_75MM_GUN_HEIGHT 32
#define DUAL_75MM_GUN_CANNON_GUN_WIDTH 129
#define DUAL_75MM_GUN_CANNON_GUN_HEIGHT 32
#define DUAL_75MM_GUN_CENTER_X_POSITION -32
#define DUAL_75MM_GUN_CENTER_Y_POSITION 15
#define DUAL_75MM_GUN_LEFT_GUN_X_POSITION 66
#define DUAL_75MM_GUN_LEFT_GUN_Y_POSITION 9
#define DUAL_75MM_GUN_MIDDLE_GUN_X_POSITION 66
#define DUAL_75MM_GUN_MIDDLE_GUN_Y_POSITION 16
#define DUAL_75MM_GUN_RIGHT_GUN_X_POSITION 66
#define DUAL_75MM_GUN_RIGHT_GUN_Y_POSITION 23
#define DUAL_75MM_GUN_FRAMES_BETWEEN_FIRE (GUNAA75MM_FRAMES_BETWEEN_FIRE)

/*------------ 7 Inch Gun -----------------*/
#define INCH_7_GUN_Z_COORDINATE NOT_IMPORTANT_Z_VALUE
#define INCH_7_GUN_WIDTH 64
#define INCH_7_GUN_HEIGHT 32
#define INCH_7_GUN_CANNON_GUN_WIDTH 128
#define INCH_7_GUN_CANNON_GUN_HEIGHT 16
#define INCH_7_GUN_CENTER_X_POSITION -12
#define INCH_7_GUN_CENTER_Y_POSITION 18
#define INCH_7_GUN_X_POSITION -20
#define INCH_7_GUN_Y_POSITION 14
#define INCH_7_GUN_PROJECTILE_X_POSITION 16
#define INCH_7_GUN_PROJECTILE_Y_POSITION 4
#define INCH_7_GUN_DEFAULT_AMMUNITION 1
#define INCH_7_GUN_DEFAULT_LIMITED_AMMUNITION FALSE
#define INCH_7_GUN_UPPER_ANGLE_RANDOM_VALUE 2
#define INCH_7_GUN_LOWER_ANGLE_RANDOM_VALUE -2
#define INCH_7_GUN_EXTRA_BULLET_SPEED_LOWER_VALUE -3
#define INCH_7_GUN_EXTRA_BULLET_SPEED_UPPER_VALUE 3
#define INCH_7_GUN_MIN_RANGE 300 //not really important
#define INCH_7_GUN_MAX_RANGE 10000
#define INCH_7_GUN_ROTATION_SPEED 1
#define INCH_7_GUN_FRAMES_BETWEEN_FIRE (GFRAMES_PER_SECOND_BACKEND * 60 * 1) // 1 min
#define INCH_7_GUN_AI_FRAME_WAIT_DELAY_UNTIL_IT_DOES_NEXT_SEARCH (GFRAMES_PER_SECOND_BACKEND * 10) //10 seconds
#define INCH_7_GUN_AI_FRAME_WAIT_DELAY_UNTIL_IT_DOES_NEXT_SEARCH_AFTER_SHOT (GFRAMES_PER_SECOND_BACKEND * 60) //1 min

/*------------ 14 Inch Gun -----------------*/
#define INCH_14_GUN_Z_COORDINATE NOT_IMPORTANT_Z_VALUE
#define INCH_14_GUN_WIDTH 92
#define INCH_14_GUN_HEIGHT 23
#define INCH_14_GUN_CANNON_GUN_WIDTH 184
#define INCH_14_GUN_CANNON_GUN_HEIGHT 12
#define INCH_14_GUN_CENTER_X_POSITION -20
#define INCH_14_GUN_CENTER_Y_POSITION 8
#define INCH_14_GUN_X_POSITION -15
#define INCH_14_GUN_Y_POSITION 3
#define INCH_14_GUN_PROJECTILE_X_POSITION 32
#define INCH_14_GUN_PROJECTILE_Y_POSITION 4
#define INCH_14_GUN_DEFAULT_AMMUNITION 1
#define INCH_14_GUN_DEFAULT_LIMITED_AMMUNITION FALSE
#define INCH_14_GUN_UPPER_ANGLE_RANDOM_VALUE 2
#define INCH_14_GUN_LOWER_ANGLE_RANDOM_VALUE -2
#define INCH_14_GUN_EXTRA_BULLET_SPEED_LOWER_VALUE -5
#define INCH_14_GUN_EXTRA_BULLET_SPEED_UPPER_VALUE 5
#define INCH_14_GUN_MIN_RANGE 500 //not really important
#define INCH_14_GUN_MAX_RANGE 25000
#define INCH_14_GUN_ROTATION_SPEED 1
#define INCH_14_GUN_FRAMES_BETWEEN_FIRE (GFRAMES_PER_SECOND_BACKEND * 60 * 2) // 2 min
#define INCH_14_GUN_AI_FRAME_WAIT_DELAY_UNTIL_IT_DOES_NEXT_SEARCH (GFRAMES_PER_SECOND_BACKEND * 20) //20 seconds
#define INCH_14_GUN_AI_FRAME_WAIT_DELAY_UNTIL_IT_DOES_NEXT_SEARCH_AFTER_SHOT (GFRAMES_PER_SECOND_BACKEND * 60 * 3) //3 min



//-------------- AI --------------//
#define HEAVY_BOMBER_AI_FRAMES_UNTIL_NEEDED_DISTANCE_CHECK 10
#define HEAVY_BOMBER_AI_FRAMES_UNTIL_RECHECK_ON_CLOSEST_TARGET (GFRAMES_PER_SECOND_BACKEND)
#define GROUND_UNIT_OVERLORD_AI_Z_VALUE NOT_IMPORTANT_Z_VALUE //not used, since it doesn't get drawn
#define GROUND_UNIT_OVERLORD_AI_HEALTH 0 //not used
#define GROUND_UNIT_OVERLORD_AI_ARMOUR 0 //not used
#define GROUND_UNIT_OVERLORD_AI_DEFAULT_FRAMES_PER_MOVE 1
#define GROUND_UNIT_OVERLORD_AI_FRAMES_UNTIL_CHECK_FOR_OTHER_ENEMY_OVERLORD (GFRAMES_PER_SECOND_BACKEND * 3)
#define GROUND_UNIT_OVERLORD_AI_DEFAULT_DISTANCE_TO_ENGAGE_TARGET (300)
#define GROUND_UNIT_OVERLORD_AI_MAX_EXTRA_DISTANCE_TO_ENGAGE_ENEMY (600)
#define GROUND_UNIT_OVERLORD_AI_TOTAL_MAX_DISTANCE_BETWEEN_TARGETS (GROUND_UNIT_OVERLORD_AI_DEFAULT_DISTANCE_TO_ENGAGE_TARGET + GROUND_UNIT_OVERLORD_AI_MAX_EXTRA_DISTANCE_TO_ENGAGE_ENEMY)


//----------------DECOR AND FLOOR---------------------//

#define DECOR_DEFAULT_Z_VALUE TREES_DEFAULT_Z_VALUE
#define BASIC_FOREST_DEFAULT_HEIGHT 128

/*------------ Flag Pole-------------*/
#define FLAG_POLE_WIDTH 4
#define FLAG_POLE_HEIGHT 128
#define FLAG_POLE_FLAG_POSITION_HEIGHT_OFFSET FLAG_POLE_HEIGHT-FLAG_POLE_FLAG_HEIGHT -3 //leave a little at the top of the Flag pole
#define FLAG_POLE_FLAG_WIDTH 64
#define FLAG_POLE_FLAG_HEIGHT 40
#define FLAG_POLE_AMERICAN_FLAG_SEQUENCE_FRAMES_UNTIL_SWITCH 5
#define FLAG_POLE_JAPANESE_FLAG_SEQUENCE_FRAMES_UNTIL_SWITCH 5

/*--------------------- Floor -----------------*/
#define FLOOR_DEFAULT_Z_COORDINATE FLOOR_DEFAULT_Z_VALUE
#define FLOOR_TEXTURE_WIDTH 16
#define FLOOR_TEXTURE_HEIGHT 8

/*--------------------- Water -----------------*/
#define WATER_TEXTURE_WIDTH 64
#define WATER_NUMBER_OF_TEXTURES 4
#define WATER_FRAMES_UNTIL_IMAGE_SWITCH 32
#define WATER_S_TEXTURE_MOVEMENT_PER_FRAME 0.004

/*--------------------- Cloud *** NOT USED ** -----------------*/
#define CLOUD_DEFAULT_Z_COORDINATE 100 //not used
#define CLOUD_TEXTURE_WIDTH 64

/*--------------------- Aircraft Smoke -----------------*/
#define AIRCRAFT_SMOKE_WIDTH 32
#define AIRCRAFT_SMOKE_HEIGHT 27
#define AIRCRAFT_SMOKE_SPEED 3
#define AIRCRAFT_SMOKE_RANGE 6000 //not really important, since it is not used
#define AIRCRAFT_SMOKE_DEFAULT_ANGEL 90 //straight up
#define AIRCRAFT_SMOKE_FRAMES_PER_IMAGE 1
#define AIRCRAFT_SMOKE_TOTAL_TIME_IN_FRAMES 150 // images are in the sequence

/*------------ DEFAULT SMOKE ------------------*/
#define DEFAULT_SMOKE_DEFAULT_ANGLE_OFFSET (-90)
#define DEFAULT_SMOKE_SPEED 5
#define DEFAULT_SMOKE_DISPLACEMENT_X 3.2
#define DEFAULT_SMOKE_DISPLACEMENT_Y 0

//----------- SHIP SMOKE ---------------------//
#define SHIP_SMOKE_DEFAULT_SIZE TSize(30, 30)
#define SHIP_SMOKE_DEFAULT_FRAMES 40

//----------- GROUND UNIT SMOKE ---------------------//
#define GROUND_UNIT_SMOKE_DEFAULT_COLOUR KColourBlack
#define GROUND_UNIT_SMOKE_STARTS_AFTER_HEALTH_LEFT 0
#define GROUND_UNIT_SMOKE_DEFAULT_SIZE TSize(25, 25)
#define GROUND_UNIT_SMOKE_DEFAULT_FRAMES 30

//----------- GROUND UNIT SMOKE ---------------------//
#define GROUND_UNIT_DUST_DEFAULT_COLOUR KColourGray
#define GROUND_UNIT_DUST_STARTS_AFTER_HEALTH_LEFT 100
#define GROUND_UNIT_DUST_DEFAULT_SIZE TSize(40, 40)
#define GROUND_UNIT_DUST_DEFAULT_FRAMES 35
#define GROUND_UNIT_DUST_DEFAULT_ANGLE_OFFSET 0
#define GROUND_UNIT_DUST_DEFAULT_SPEED TIntFloat::Convert(-5)
#define GROUND_UNIT_DUST_DEFAULT_X_EXPO TIntFloat::Convert(0)
#define GROUND_UNIT_DUST_DEFAULT_Y_EXPO TIntFloat::Convert(2)


/*------------ Aircraft Smoke Creator ------------------*/
#define AIRCRAFT_SMOKE_CREATOR_WHEN_CRASHED_WIDTH 18
#define AIRCRAFT_SMOKE_CREATOR_WHEN_CRASHED_ANGLE DEFAULT_SMOKE_DEFAULT_ANGLE
#define AIRCRAFT_SMOKE_CREATOR_WHEN_CRASHED_SMOKE_SPEED DEFAULT_SMOKE_SPEED
#define AIRCRAFT_SOMKE_CREATOR_WHEN_CRASHED_FRAMES_FOR_SMOKE 40
#define AIRCRAFT_SOMKE_CREATOR_WHEN_CRASHED_SMOKE_DISPLACEMENT_X DEFAULT_SMOKE_DISPLACEMENT_X
#define AIRCRAFT_SOMKE_CREATOR_WHEN_CRASHED_SMOKE_DISPLACEMENT_Y DEFAULT_SMOKE_DISPLACEMENT_Y




/*-----------------------Forest 1------------------*/
#define FOREST1_DEFAULT_Z_COORDINATE TREES_DEFAULT_Z_VALUE //just to make sure that forests of different kinds can overlap
#define FOREST1_TOTAL_WIDTH 503
#define FOREST1_SMALL_TREE1_OFFSET 51
#define FOREST1_SMALL_TREE2_OFFSET 147
#define FOREST1_SMALL_TREE3_OFFSET 247
#define FOREST1_SMALL_TREE4_OFFSET 343
#define FOREST1_SMALL_TREE5_OFFSET 405
#define FOREST1_BIG_TREE1_OFFSET 0
#define FOREST1_BIG_TREE2_OFFSET 147
#define FOREST1_BIG_TREE3_OFFSET 235
#define FOREST1_THIN_BIG_TREE1_OFFSET 115
#define FOREST1_THIN_BIG_TREE2_OFFSET 215
#define FOREST1_THIN_BIG_TREE3_OFFSET 375

/*-----------------------Forest 2------------------*/
//Total Width to the right is 271
#define FOREST2_DEFAULT_Z_COORDINATE TREES_DEFAULT_Z_VALUE //just to make sure that forests of different kinds can overlap
#define FOREST2_TOTAL_WIDTH 271
#define FOREST2_SMALL_TREE1_OFFSET 100
#define FOREST2_BIG_TREE1_OFFSET 0
#define FOREST2_BIG_TREE2_OFFSET 143

/*-----------------------Forest 3------------------*/
//Total Width to the right is 692
#define FOREST3_DEFAULT_Z_COORDINATE TREES_DEFAULT_Z_VALUE //just to make sure that forests of different kinds can overlap
#define FOREST3_TOTAL_WIDTH 692
#define FOREST3_SMALL_TREE1_OFFSET 0
#define FOREST3_SMALL_TREE2_OFFSET 628
#define FOREST3_BIG_TREE1_OFFSET 200
#define FOREST3_BIG_TREE2_OFFSET 300

/*-----------------------Forest 4------------------*/
//Total Width to the right is 849
#define FOREST4_DEFAULT_Z_COORDINATE TREES_DEFAULT_Z_VALUE //just to make sure that forests of different kinds can overlap
#define FOREST4_TOTAL_WIDTH 849
#define FOREST4_SMALL_TREE1_OFFSET 0
#define FOREST4_SMALL_TREE2_OFFSET 350
#define FOREST4_SMALL_TREE3_OFFSET 710
#define FOREST4_SMALL_TREE4_OFFSET 785
#define FOREST4_BIG_TREE1_OFFSET 150
#define FOREST4_BIG_TREE2_OFFSET 460
#define FOREST4_THIN_BIG_TREE1_OFFSET 420


/*--------------------- Trees -----------------*/
#define TREE_DEFAULT_Z_COORDINATE TREES_DEFAULT_Z_VALUE
#define TREE1_DEFAULT_WIDHT 32 //max 32
#define TREE1_DEFAULT_HEIGHT 128 //max 128

#define TREE_BIG_TREE_DEFAULT_WIDHT 128 //max 32
#define TREE_BIG_TREE_DEFAULT_HEIGHT 128 //max 128
#define TREE_BIG_TREE_HITBOX_HEIGHT 120 //max 128
#define TREE_BIG_TREE_HITBOX_WIDTH 125 //max 128

#define TREE_SMALL_TREE_DEFAULT_WIDHT 64 //max 32
#define TREE_SMALL_TREE_DEFAULT_HEIGHT 64 //max 128

#define TREE_PALM_TREE_Z_COORDINATE TREES_DEFAULT_Z_VALUE
#define TREE2_DEFAULT_WIDHT 64 //max 64
#define TREE2_DEFAULT_HEIGHT 64 //max 64
#define TREE2_SMALLER_Y_OFFSET -14 // if the tree is member of the smaller category move it down by 20 pixels
#define TREE2_Y_COLLISION_BOX_ADJUSTMENT -7


#define TREE3_DEFAULT_WIDH 32 //max 16
#define TREE3_DEFAULT_HEIGHT 32 //max 32

/*--------- BASIC BACKGROUD --------*/
#define BACKGROUND_BASIC_Z_VALUE NOT_IMPORTANT_Z_VALUE //should be the last thing to be drawn, so that only pixels for the background get drawn that need to be
#define BACKGROUND_BASIC_CLOUD_MOVE_SPEED 0.0004
#define BACKGROUND_BASIC_WIDTH 1024
#define BACKGROUND_BASIC_HEIGHT 609
#define BACKGROUND_TEXTURE_SIZE 1024
#define BACKGROUND_BASIC_DEFAULT_LOWER_T_VALUE 0
#define BACKGROUND_BASIC_DEFAULT_UPPER_T_VALUE ((TFloat) -BACKGROUND_BASIC_HEIGHT / BACKGROUND_TEXTURE_SIZE)

#define HUD_BASIC_Z_VALUE NOT_IMPORTANT_Z_VALUE

#endif /* GAMEOBJECTDEFAULTVALUES_H_ */
