/*
 * GameObjectDefaultValuesMedium.h
 *
 *  Created on: 2011-01-03
 *      Author: dstoll
 */

#ifndef GAMEOBJECTDEFAULTVALUESMEDIUM_H_
#define GAMEOBJECTDEFAULTVALUESMEDIUM_H_

//--------------- Player Lives -------------------//
#define PLAYER_NUMBER_OF_LIVES_MEDIUM 5

//----------------Aircarfts---------------------//

/*---------------US Navy Close Air Support: Dauntless-------------------*/
#define DAUNTLESS_DEFAULT_HEALTH_MEDIUM 160
#define DAUNTLESS_1000KG_BOMB_MAX_LOAD_MEDIUM 4
#define DAUNTLESS_500KG_BOMB_MAX_LOAD_MEDIUM 8
#define DAUNTLESS_100KG_BOMB_MAX_LOAD_MEDIUM 30
#define DAUNTLESS_CLUSTER_BOMB_MAX_LOAD_MEDIUM 4
#define DAUNTLESS_TORPEDO_MAX_LOAD_MEDIUM 4
#define DAUNTLESS_STANDARD_ROCKET_MAX_LOAD_MEDIUM 10
/*---------------US Navy Medium Bomber: Mitchell (B-25)-------------------*/
#define MITCHELL_DEFAULT_HEALTH_MEDIUM 300
#define MITCHELL_1000KG_BOMB_MAX_LOAD_MEDIUM 8
#define MITCHELL_500KG_BOMB_MAX_LOAD_MEDIUM 10

/*---------------Japanese Imperial Dive Bomber: Val(Aichi D3A)-------------------*/
#define VAL_DEFAULT_HEALTH_MEDIUM 100
#define VAL_1000KG_BOMB_MAX_LOAD_MEDIUM 2
#define VAL_500KG_BOMB_MAX_LOAD_MEDIUM 4
#define VAL_100KG_BOMB_MAX_LOAD_MEDIUM 20
#define VAL_CLUSTER_BOMB_MAX_LOAD_MEDIUM 2
#define VAL_TORPEDO_MAX_LOAD_MEDIUM 2 //was 3
#define VAL_STANDARD_ROCKET_MAX_LOAD_MEDIUM 2
/*---------------Imperial Japanese Navy Bomber: Betty(Mitsubishi G4M1)-------------------*/
#define BETTY_DEFAULT_HEALTH_MEDIUM 150
#define BETTY_1000KG_BOMB_MAX_LOAD_MEDIUM 4
#define BETTY_500KG_BOMB_MAX_LOAD_MEDIUM 5

//-------------------------- SHIPS -----------------------//

//USS Ships
#define USS_VICTORY_HEALTH_MEDIUM 42000
#define AMERICAN_CARRIER_HEALTH_MEDIUM 35000
#define AMERICAN_LCT_HEALTH_MEDIUM 1000
#define AMERICAN_DESTROYER_HEALTH_MEDIUM 14000
#define AMERICAN_BATTLESHIP_USS_TENNESSEE_HEALTH_MEDIUM 35000
#define AMERICAN_TROOP_TRANSPORTER_HEALTH_MEDIUM 7000
//Japanese Ships
#define JAPANESE_LCT_HEALTH_MEDIUM 1500
#define JAPANESE_CARRIER_HEALTH_MEDIUM 40000
#define JAPANESE_DESTROYER_HEALTH_MEDIUM 17000
#define JAPANESE_BATTLESHIP_YAMATO_HEALTH_MEDIUM 52500
#define JAPANESE_TROOP_TRANSPORTER_HEALTH_MEDIUM 10000
#define JAPANESE_OIL_TANKER_HEALTH_MEDIUM 10000


#endif /* GAMEOBJECTDEFAULTVALUESMEDIUM_H_ */
