/*
 * GameObjectDefaultValuesEasy.h
 *
 *  Created on: 2011-01-03
 *      Author: dstoll
 */

#ifndef GAMEOBJECTDEFAULTVALUESEASY_H_
#define GAMEOBJECTDEFAULTVALUESEASY_H_

//--------------- Player Lives -------------------//
#define PLAYER_NUMBER_OF_LIVES_EASY 9

//----------------Aircarfts---------------------//

/*---------------US Navy Close Air Support: Dauntless-------------------*/
#define DAUNTLESS_DEFAULT_HEALTH_EASY 300
#define DAUNTLESS_1000KG_BOMB_MAX_LOAD_EASY 6
#define DAUNTLESS_500KG_BOMB_MAX_LOAD_EASY 12
#define DAUNTLESS_100KG_BOMB_MAX_LOAD_EASY 40
#define DAUNTLESS_CLUSTER_BOMB_MAX_LOAD_EASY 6
#define DAUNTLESS_TORPEDO_MAX_LOAD_EASY 6
#define DAUNTLESS_STANDARD_ROCKET_MAX_LOAD_EASY 20
/*---------------US Navy Medium Bomber: Mitchell (B-25)-------------------*/
#define MITCHELL_DEFAULT_HEALTH_EASY 400
#define MITCHELL_1000KG_BOMB_MAX_LOAD_EASY 8
#define MITCHELL_500KG_BOMB_MAX_LOAD_EASY 10

/*---------------Japanese Imperial Dive Bomber: Val(Aichi D3A)-------------------*/
#define VAL_DEFAULT_HEALTH_EASY 100
#define VAL_1000KG_BOMB_MAX_LOAD_EASY 2
#define VAL_500KG_BOMB_MAX_LOAD_EASY 4
#define VAL_100KG_BOMB_MAX_LOAD_EASY 20
#define VAL_CLUSTER_BOMB_MAX_LOAD_EASY 2
#define VAL_TORPEDO_MAX_LOAD_EASY 2 //was 3
#define VAL_STANDARD_ROCKET_MAX_LOAD_EASY 2
/*---------------Imperial Japanese Navy Bomber: Betty(Mitsubishi G4M1)-------------------*/
#define BETTY_DEFAULT_HEALTH_EASY 100
#define BETTY_1000KG_BOMB_MAX_LOAD_EASY 2
#define BETTY_500KG_BOMB_MAX_LOAD_EASY 2



//-------------------------- SHIPS -----------------------//

//USS Ships
#define USS_VICTORY_HEALTH_EASY 42000
#define AMERICAN_CARRIER_HEALTH_EASY 35000
#define AMERICAN_LCT_HEALTH_EASY 1000
#define AMERICAN_DESTROYER_HEALTH_EASY 14000
#define AMERICAN_BATTLESHIP_USS_TENNESSEE_HEALTH_EASY 35000
#define AMERICAN_TROOP_TRANSPORTER_HEALTH_EASY 7000
//Japanese Ships
#define JAPANESE_LCT_HEALTH_EASY 1000
#define JAPANESE_CARRIER_HEALTH_EASY 35000
#define JAPANESE_DESTROYER_HEALTH_EASY 14000
#define JAPANESE_BATTLESHIP_YAMATO_HEALTH_EASY 52500
#define JAPANESE_TROOP_TRANSPORTER_HEALTH_EASY 7000
#define JAPANESE_OIL_TANKER_HEALTH_EASY 7000


#endif /* GAMEOBJECTDEFAULTVALUESEASY_H_ */
