#ifndef GAMEOBJECTSINCLUDES_H_
#define GAMEOBJECTSINCLUDES_H_

//AI
#include "includes/game/backend/gameObjects/AI/CAAArteriallyAI.h"
#include "includes/game/backend/gameObjects/AI/CHeavyBomberAI.h"
#include "includes/game/backend/gameObjects/AI/CBackCannonAI.h"
#include "includes/game/backend/gameObjects/AI/CGroundUnitOverlordAI.h"
#include "includes/game/backend/gameObjects/AI/CFighterAI.h"
#include "includes/game/backend/gameObjects/AI/CShipArteriallyAI.h"

//Airplanes
#include "includes/game/backend/gameObjects/Aircrafts/CDauntless.h"
#include "includes/game/backend/gameObjects/Aircrafts/CBetty.h"
#include "includes/game/backend/gameObjects/Aircrafts/CMitchell.h"
#include "includes/game/backend/gameObjects/Aircrafts/CVal.h"

//Ships
#include "includes/game/backend/gameObjects/Ships/CUSSVictory.h"
#include "includes/game/backend/gameObjects/Ships/CAmericanLCT.h"
#include "includes/game/backend/gameObjects/Ships/CAmericanCarrierLexington.h"
#include "includes/game/backend/gameObjects/Ships/CAmericanDestroyer.h"
#include "includes/game/backend/gameObjects/Ships/CAmericanBattleshipUSSTennessee.h"
#include "includes/game/backend/gameObjects/Ships/CAmericanTroopTransporter.h"
#include "includes/game/backend/gameObjects/Ships/CJapaneseLCT.h"
#include "includes/game/backend/gameObjects/Ships/CJapaneseCarrierShoho.h"
#include "includes/game/backend/gameObjects/Ships/CJapaneseCarrierShokaku.h"
#include "includes/game/backend/gameObjects/Ships/CJapaneseCarrierTaiho.h"
#include "includes/game/backend/gameObjects/Ships/CJapaneseDestroyer.h"
#include "includes/game/backend/gameObjects/Ships/CJapaneseBattleshipYamato.h"
#include "includes/game/backend/gameObjects/Ships/CJapaneseTroopTransporter.h"
#include "includes/game/backend/gameObjects/Ships/CJapaneseOilTanker.h"

//Projectiles
#include "includes/game/backend/gameObjects/Projectiles/CPropelledGrenade.h"
#include "includes/game/backend/gameObjects/Projectiles/CBulletRifle.h"
#include "includes/game/backend/gameObjects/Projectiles/CBulletCannon20mm.h"
#include "includes/game/backend/gameObjects/Projectiles/CBullet13mm.h"
#include "includes/game/backend/gameObjects/Projectiles/CBullet8mm.h"
#include "includes/game/backend/gameObjects/Projectiles/CBomb1000kg.h"
#include "includes/game/backend/gameObjects/Projectiles/CBomb500kg.h"
#include "includes/game/backend/gameObjects/Projectiles/CExplosive88mmShell.h"
#include "includes/game/backend/gameObjects/Projectiles/CExplosive75mmShell.h"
#include "includes/game/backend/gameObjects/Projectiles/CStandardRocket.h"
#include "includes/game/backend/gameObjects/Projectiles/CBomb100kg.h"
#include "includes/game/backend/gameObjects/Projectiles/CClusterBomb.h"
#include "includes/game/backend/gameObjects/Projectiles/CTorpedo.h"
#include "includes/game/backend/gameObjects/Projectiles/CUnderWaterTorpedo.h"
#include "includes/game/backend/gameObjects/Projectiles/CTankShell80mm.h"
#include "includes/game/backend/gameObjects/Projectiles/CExplosive7InchShell.h"
#include "includes/game/backend/gameObjects/Projectiles/CExplosive14InchShell.h"

//Ground Units
#include "includes/game/backend/gameObjects/GroundUnits/CJapaneseRifleman.h"
#include "includes/game/backend/gameObjects/GroundUnits/CJapaneseRocketman.h"
#include "includes/game/backend/gameObjects/GroundUnits/CJapanese97ChiHaTank.h"
#include "includes/game/backend/gameObjects/GroundUnits/CJapaneseAA97ChiHaTank.h"
#include "includes/game/backend/gameObjects/GroundUnits/CAmericanRifleman.h"
#include "includes/game/backend/gameObjects/GroundUnits/CAmericanRocketman.h"
#include "includes/game/backend/gameObjects/GroundUnits/CAmericanShermanTank.h"
#include "includes/game/backend/gameObjects/GroundUnits/CAmericanAAShermanTank.h"
#include "includes/game/backend/gameObjects/GroundUnits/CAmericanSquad.h"
#include "includes/game/backend/gameObjects/GroundUnits/CJapaneseSquad.h"

//Land
#include "includes/game/backend/gameObjects/Floor/CFloorLand.h"
#include "includes/game/backend/gameObjects/Floor/CFloorWater.h"

//Buildings
#include "includes/game/backend/gameObjects/Buildings/CJapaneseAAConcrete.h"
#include "includes/game/backend/gameObjects/Buildings/CJapaneseAA75mmType88.h"
#include "includes/game/backend/gameObjects/Buildings/CJapaneseAA20mmMachineCannon.h"
#include "includes/game/backend/gameObjects/Buildings/CAirport.h"
#include "includes/game/backend/gameObjects/Buildings/CHangar.h"
#include "includes/game/backend/gameObjects/Buildings/CFlagPole.h"
#include "includes/game/backend/gameObjects/Buildings/CHq.h"
#include "includes/game/backend/gameObjects/Buildings/CComStation.h"

//Decor
#include "includes/game/backend/gameObjects/Decor/CForest1.h"
#include "includes/game/backend/gameObjects/Decor/CForest2.h"
#include "includes/game/backend/gameObjects/Decor/CForest3.h"
#include "includes/game/backend/gameObjects/Decor/CForest4.h"
#include "includes/game/backend/gameObjects/Decor/CTree1.h"
#include "includes/game/backend/gameObjects/Decor/CTree2.h"
#include "includes/game/backend/gameObjects/Decor/CBigTree.h"
#include "includes/game/backend/gameObjects/Decor/CSmallTree.h"
#include "includes/game/backend/gameObjects/Decor/CAircraftSmokeCreator.h"
#include "includes/game/backend/gameObjects/Decor/CGeneralSmokeCreator.h"
#include "includes/game/backend/gameObjects/Decor/CSmoke.h"
//
//Explosions
#include "includes/game/backend/gameObjects/Explosions/CExplosion14InchShell.h"
#include "includes/game/backend/gameObjects/Explosions/CExplosion14InchShellInWater.h"
#include "includes/game/backend/gameObjects/Explosions/CExplosion1000Kg.h"
#include "includes/game/backend/gameObjects/Explosions/CExplosion100KgInAir.h"
#include "includes/game/backend/gameObjects/Explosions/CExplosion500Kg.h"
#include "includes/game/backend/gameObjects/Explosions/CExplosion1000KgInAir.h"
#include "includes/game/backend/gameObjects/Explosions/CExplosion500KgInAir.h"
#include "includes/game/backend/gameObjects/Explosions/CExplosion100Kg.h"
#include "includes/game/backend/gameObjects/Explosions/CExplosion1000KgInWater.h"
#include "includes/game/backend/gameObjects/Explosions/CExplosion500KgInWater.h"
#include "includes/game/backend/gameObjects/Explosions/CExplosion100KgInWater.h"
#include "includes/game/backend/gameObjects/Explosions/CWaterSplash.h"

//Weapons
#include "includes/game/backend/gameObjects/Weapons/CMachineGun13mm.h"
#include "includes/game/backend/gameObjects/Weapons/CMachineGun8mm.h"
#include "includes/game/backend/gameObjects/Weapons/CWeaponAircraftMachineGun13mm.h"
#include "includes/game/backend/gameObjects/Weapons/CWeaponAircraftMachineGun8mm.h"
#include "includes/game/backend/gameObjects/Weapons/CBackGunMachineGun8mm.h"
#include "includes/game/backend/gameObjects/Weapons/CBackGunDoubleMachineGun8mm.h"
#include "includes/game/backend/gameObjects/Weapons/CBackGunDoubleMachineGun13mm.h"
#include "includes/game/backend/gameObjects/Weapons/CRifle.h"
#include "includes/game/backend/gameObjects/Weapons/CGrenadeLauncher.h"
#include "includes/game/backend/gameObjects/Weapons/CWeaponBomb1000Kg.h"
#include "includes/game/backend/gameObjects/Weapons/CWeaponBomb500Kg.h"
#include "includes/game/backend/gameObjects/Weapons/CGunAA88mm.h"
#include "includes/game/backend/gameObjects/Weapons/CGunAA75mm.h"
#include "includes/game/backend/gameObjects/Weapons/CStandardRocketWeapon.h"
#include "includes/game/backend/gameObjects/Weapons/CWeaponBomb100Kg.h"
#include "includes/game/backend/gameObjects/Weapons/CWeaponBombCluster.h"
#include "includes/game/backend/gameObjects/Weapons/CWeaponTorpedo.h"
#include "includes/game/backend/gameObjects/Weapons/CTankGun80mm.h"
#include "includes/game/backend/gameObjects/Weapons/CTankAAGun.h"
#include "includes/game/backend/gameObjects/Weapons/CShipDualMachineGun.h"
#include "includes/game/backend/gameObjects/Weapons/CShipDual75mmGun.h"
#include "includes/game/backend/gameObjects/Weapons/CGun7Inch.h"
#include "includes/game/backend/gameObjects/Weapons/CGun14Inch.h"
#include "includes/game/backend/gameObjects/Weapons/CExplosive7InchGun.h"
#include "includes/game/backend/gameObjects/Weapons/CExplosive14InchGun.h"

//other
#include "includes/game/backend/basicClasses/CBackgroundImage.h"

//Events
#include "includes/game/backend/gameObjects/Events/CWinIfObjectsAreDestroyedEvent.h"
#include "includes/game/backend/gameObjects/Events/CWinIfAllJapaneseForcesAreDestroyed.h"
#include "includes/game/backend/gameObjects/Events/CWinIfAllJapaneseMoveableObjectsAreDestroyed.h"
#include "includes/game/backend/gameObjects/Events/CWinIfObjectsLeaveMapAlive.h"
#include "includes/game/backend/gameObjects/Events/CWinIfObjectsAreCaptured.h"
#include "includes/game/backend/gameObjects/Events/CWinIfJapaneseDestroyedAfterACertainTime.h"
#include "includes/game/backend/gameObjects/Events/CLoseIfObjectsAreDestroyedEvent.h"
#include "includes/game/backend/gameObjects/Events/CLoseIfObjectsAreCaptured.h"
#include "includes/game/backend/gameObjects/Events/CLoseIfObjectLeavesMap.h"
#include "includes/game/backend/gameObjects/Events/CGetBonusPointsIfObjectsAreDestroyedEvent.h"
#include "includes/game/backend/gameObjects/Events/CGetBonusPointsIfObjectsSurvive.h"
#include "includes/game/backend/gameObjects/Events/CGetBonusPointsIfLessTroopsGetKilled.h"
#include "includes/game/backend/gameObjects/Events/CCreateMitchellToAttackTargetClockTimer.h"
#include "includes/game/backend/gameObjects/Events/CSpawnBettyEveryTimeInterval.h"
#include "includes/game/backend/gameObjects/Events/CSpawnMitchellEveryTimeInterval.h"
#include "includes/game/backend/gameObjects/Events/CSpawnDauntlessEveryTimeInterval.h"
#include "includes/game/backend/gameObjects/Events/CSpawnDauntlessIfBuildingGetsCaptured.h"
#include "includes/game/backend/gameObjects/Events/CSpawnAmericanLCTEveryTimeInterval.h"
#include "includes/game/backend/gameObjects/Events/CSpawnAmericanSquadEveryTimeInterval.h"
#include "includes/game/backend/gameObjects/Events/CSpawnAmericanTroopTransporterIfObjectsDestroyed.h"
#include "includes/game/backend/gameObjects/Events/CSpawnJapaneseSquadEveryTimeInterval.h"
#include "includes/game/backend/gameObjects/Events/CSpawnJapaneseSquadIfBuildingGetsCaptured.h"
#include "includes/game/backend/gameObjects/Events/CSpawnBettyIfBuildingGetsCaptured.h"
#include "includes/game/backend/gameObjects/Events/CSpawnValIfBuildingGetsCaptured.h"
#include "includes/game/backend/gameObjects/Events/CSpawnValEveryTimeInterval.h"
#include "includes/game/backend/gameObjects/Events/CClockTimerEvent.h"

#endif
