/*
 * GameObjectDefaultValuesHard.h
 *
 *  Created on: 2011-01-03
 *      Author: dstoll
 */

#ifndef GAMEOBJECTDEFAULTVALUESHARD_H_
#define GAMEOBJECTDEFAULTVALUESHARD_H_

//--------------- Player Lives -------------------//
#define PLAYER_NUMBER_OF_LIVES_HARD 3

//----------------Aircarfts---------------------//

/*---------------US Navy Close Air Support: Dauntless-------------------*/
#define DAUNTLESS_DEFAULT_HEALTH_HARD 100
#define DAUNTLESS_1000KG_BOMB_MAX_LOAD_HARD 2
#define DAUNTLESS_500KG_BOMB_MAX_LOAD_HARD 4
#define DAUNTLESS_100KG_BOMB_MAX_LOAD_HARD 20
#define DAUNTLESS_CLUSTER_BOMB_MAX_LOAD_HARD 3
#define DAUNTLESS_TORPEDO_MAX_LOAD_HARD 2
#define DAUNTLESS_STANDARD_ROCKET_MAX_LOAD_HARD 4
/*---------------US Navy Medium Bomber: Mitchell (B-25)-------------------*/
#define MITCHELL_DEFAULT_HEALTH_HARD 200
#define MITCHELL_1000KG_BOMB_MAX_LOAD_HARD 8
#define MITCHELL_500KG_BOMB_MAX_LOAD_HARD 10

/*---------------Japanese Imperial Dive Bomber: Val(Aichi D3A)-------------------*/
#define VAL_DEFAULT_HEALTH_HARD 100
#define VAL_1000KG_BOMB_MAX_LOAD_HARD 2
#define VAL_500KG_BOMB_MAX_LOAD_HARD 4
#define VAL_100KG_BOMB_MAX_LOAD_HARD 20
#define VAL_CLUSTER_BOMB_MAX_LOAD_HARD 3
#define VAL_TORPEDO_MAX_LOAD_HARD 2 //was 3
#define VAL_STANDARD_ROCKET_MAX_LOAD_HARD 4
/*---------------Imperial Japanese Navy Bomber: Betty(Mitsubishi G4M1)-------------------*/
#define BETTY_DEFAULT_HEALTH_HARD 200
#define BETTY_1000KG_BOMB_MAX_LOAD_HARD 8
#define BETTY_500KG_BOMB_MAX_LOAD_HARD 10

//-------------------------- SHIPS -----------------------//

//USS Ships
#define USS_VICTORY_HEALTH_HARD 42000
#define AMERICAN_CARRIER_HEALTH_HARD 35000
#define AMERICAN_LCT_HEALTH_HARD 1000
#define AMERICAN_DESTROYER_HEALTH_HARD 14000
#define AMERICAN_BATTLESHIP_USS_TENNESSEE_HEALTH_HARD 35000
#define AMERICAN_TROOP_TRANSPORTER_HEALTH_HARD 7000
//Japanese Ships
#define JAPANESE_LCT_HEALTH_HARD 3000
#define JAPANESE_CARRIER_HEALTH_HARD 44000
#define JAPANESE_DESTROYER_HEALTH_HARD 20000
#define JAPANESE_BATTLESHIP_YAMATO_HEALTH_HARD 60000
#define JAPANESE_TROOP_TRANSPORTER_HEALTH_HARD 14000
#define JAPANESE_OIL_TANKER_HEALTH_HARD 14000


#endif /* GAMEOBJECTDEFAULTVALUESHARD_H_ */
